/**
 * Curriculum -> Practice Problem Coverage Map
 * Maps each of the 160 learning days to corresponding verified practice problems.
 * This metadata connects the learning curriculum to the practice portal cleanly
 * without imposing hard runtime gating.
 */

export interface CurriculumPracticeMapping {
  day_number: number;
  topic_name: string;
  primary_problem_slug: string;
  practice_problem_slugs: string[];
  difficulty_tier: number;
  required: boolean;
}

export const CURRICULUM_PRACTICE_MAP: Record<number, CurriculumPracticeMapping> = {
  1: {
    day_number: 1,
    topic_name: "python-basics",
    primary_problem_slug: "celsius-to-fahrenheit",
    practice_problem_slugs: ["celsius-to-fahrenheit"],
    difficulty_tier: 1,
    required: true,
  },
  2: {
    day_number: 2,
    topic_name: "python-basics",
    primary_problem_slug: "time-converter-seconds",
    practice_problem_slugs: ["time-converter-seconds"],
    difficulty_tier: 1,
    required: true,
  },
  3: {
    day_number: 3,
    topic_name: "python-basics",
    primary_problem_slug: "slice-url-domain",
    practice_problem_slugs: ["slice-url-domain"],
    difficulty_tier: 1,
    required: true,
  },
  4: {
    day_number: 4,
    topic_name: "python-basics",
    primary_problem_slug: "leap-year-checker",
    practice_problem_slugs: ["leap-year-checker"],
    difficulty_tier: 1,
    required: true,
  },
  5: {
    day_number: 5,
    topic_name: "python-basics",
    primary_problem_slug: "sum-multiples-loop",
    practice_problem_slugs: ["sum-multiples-loop"],
    difficulty_tier: 1,
    required: true,
  },
  6: {
    day_number: 6,
    topic_name: "python-basics",
    primary_problem_slug: "count-loop-operations",
    practice_problem_slugs: ["count-loop-operations"],
    difficulty_tier: 1,
    required: true,
  },
  7: {
    day_number: 7,
    topic_name: "python-basics",
    primary_problem_slug: "common-keys-intersection",
    practice_problem_slugs: ["common-keys-intersection"],
    difficulty_tier: 1,
    required: true,
  },
  8: {
    day_number: 8,
    topic_name: "python-basics",
    primary_problem_slug: "recursive-sum-digits",
    practice_problem_slugs: ["recursive-sum-digits"],
    difficulty_tier: 1,
    required: true,
  },
  9: {
    day_number: 9,
    topic_name: "python-basics",
    primary_problem_slug: "flatten-2d-matrix",
    practice_problem_slugs: ["flatten-2d-matrix"],
    difficulty_tier: 1,
    required: true,
  },
  10: {
    day_number: 10,
    topic_name: "python-basics",
    primary_problem_slug: "vector2d-operations",
    practice_problem_slugs: ["vector2d-operations"],
    difficulty_tier: 2,
    required: true,
  },
  11: {
    day_number: 11,
    topic_name: "python-basics",
    primary_problem_slug: "remove-element",
    practice_problem_slugs: ["remove-element"],
    difficulty_tier: 1,
    required: true,
  },
  12: {
    day_number: 12,
    topic_name: "python-basics",
    primary_problem_slug: "merge-sorted-array",
    practice_problem_slugs: ["merge-sorted-array"],
    difficulty_tier: 1,
    required: true,
  },
  13: {
    day_number: 13,
    topic_name: "python-basics",
    primary_problem_slug: "group-by-parity",
    practice_problem_slugs: ["group-by-parity"],
    difficulty_tier: 1,
    required: true,
  },
  14: {
    day_number: 14,
    topic_name: "python-basics",
    primary_problem_slug: "find-the-difference",
    practice_problem_slugs: ["find-the-difference"],
    difficulty_tier: 1,
    required: true,
  },
  15: {
    day_number: 15,
    topic_name: "python-basics",
    primary_problem_slug: "string-to-integer-atoi",
    practice_problem_slugs: ["string-to-integer-atoi"],
    difficulty_tier: 2,
    required: true,
  },
  16: {
    day_number: 16,
    topic_name: "python-basics",
    primary_problem_slug: "sliding-window-deque",
    practice_problem_slugs: ["sliding-window-deque"],
    difficulty_tier: 2,
    required: true,
  },
  17: {
    day_number: 17,
    topic_name: "python-basics",
    primary_problem_slug: "power-of-three",
    practice_problem_slugs: ["power-of-three"],
    difficulty_tier: 1,
    required: true,
  },
  18: {
    day_number: 18,
    topic_name: "python-basics",
    primary_problem_slug: "powx-n",
    practice_problem_slugs: ["powx-n"],
    difficulty_tier: 2,
    required: true,
  },
  19: {
    day_number: 19,
    topic_name: "python-basics",
    primary_problem_slug: "subsets-recursive",
    practice_problem_slugs: ["subsets-recursive"],
    difficulty_tier: 2,
    required: true,
  },
  20: {
    day_number: 20,
    topic_name: "python-basics",
    primary_problem_slug: "generate-parentheses",
    practice_problem_slugs: ["generate-parentheses"],
    difficulty_tier: 2,
    required: true,
  },
  21: {
    day_number: 21,
    topic_name: "python-basics",
    primary_problem_slug: "palindrome-number",
    practice_problem_slugs: ["palindrome-number"],
    difficulty_tier: 1,
    required: true,
  },
  22: {
    day_number: 22,
    topic_name: "python-basics",
    primary_problem_slug: "sort-colors",
    practice_problem_slugs: ["sort-colors"],
    difficulty_tier: 2,
    required: true,
  },
  23: {
    day_number: 23,
    topic_name: "arrays",
    primary_problem_slug: "contains-duplicate",
    practice_problem_slugs: ["contains-duplicate"],
    difficulty_tier: 1,
    required: true,
  },
  24: {
    day_number: 24,
    topic_name: "arrays",
    primary_problem_slug: "two-sum",
    practice_problem_slugs: ["two-sum"],
    difficulty_tier: 1,
    required: true,
  },
  25: {
    day_number: 25,
    topic_name: "strings",
    primary_problem_slug: "valid-anagram",
    practice_problem_slugs: ["valid-anagram"],
    difficulty_tier: 1,
    required: true,
  },
  26: {
    day_number: 26,
    topic_name: "arrays",
    primary_problem_slug: "running-sum",
    practice_problem_slugs: ["running-sum"],
    difficulty_tier: 1,
    required: true,
  },
  27: {
    day_number: 27,
    topic_name: "arrays",
    primary_problem_slug: "range-sum-query-immutable",
    practice_problem_slugs: ["range-sum-query-immutable"],
    difficulty_tier: 1,
    required: true,
  },
  28: {
    day_number: 28,
    topic_name: "arrays",
    primary_problem_slug: "range-sum-query-2d-immutable",
    practice_problem_slugs: ["range-sum-query-2d-immutable"],
    difficulty_tier: 2,
    required: true,
  },
  29: {
    day_number: 29,
    topic_name: "arrays",
    primary_problem_slug: "max-consecutive-ones",
    practice_problem_slugs: ["max-consecutive-ones"],
    difficulty_tier: 1,
    required: true,
  },
  30: {
    day_number: 30,
    topic_name: "arrays",
    primary_problem_slug: "product-except-self",
    practice_problem_slugs: ["product-except-self"],
    difficulty_tier: 2,
    required: true,
  },
  31: {
    day_number: 31,
    topic_name: "arrays",
    primary_problem_slug: "merge-intervals",
    practice_problem_slugs: ["merge-intervals"],
    difficulty_tier: 2,
    required: true,
  },
  32: {
    day_number: 32,
    topic_name: "arrays",
    primary_problem_slug: "move-zeroes",
    practice_problem_slugs: ["move-zeroes"],
    difficulty_tier: 1,
    required: true,
  },
  33: {
    day_number: 33,
    topic_name: "arrays",
    primary_problem_slug: "max-subarray",
    practice_problem_slugs: ["max-subarray"],
    difficulty_tier: 2,
    required: true,
  },
  34: {
    day_number: 34,
    topic_name: "strings",
    primary_problem_slug: "longest-common-prefix",
    practice_problem_slugs: ["longest-common-prefix"],
    difficulty_tier: 1,
    required: true,
  },
  35: {
    day_number: 35,
    topic_name: "strings",
    primary_problem_slug: "reverse-words",
    practice_problem_slugs: ["reverse-words"],
    difficulty_tier: 2,
    required: true,
  },
  36: {
    day_number: 36,
    topic_name: "two-pointers",
    primary_problem_slug: "valid-palindrome",
    practice_problem_slugs: ["valid-palindrome"],
    difficulty_tier: 1,
    required: true,
  },
  37: {
    day_number: 37,
    topic_name: "two-pointers",
    primary_problem_slug: "two-sum-sorted",
    practice_problem_slugs: ["two-sum-sorted"],
    difficulty_tier: 2,
    required: true,
  },
  38: {
    day_number: 38,
    topic_name: "two-pointers",
    primary_problem_slug: "three-sum",
    practice_problem_slugs: ["three-sum"],
    difficulty_tier: 3,
    required: true,
  },
  39: {
    day_number: 39,
    topic_name: "two-pointers",
    primary_problem_slug: "container-most-water",
    practice_problem_slugs: ["container-most-water"],
    difficulty_tier: 3,
    required: true,
  },
  40: {
    day_number: 40,
    topic_name: "two-pointers",
    primary_problem_slug: "trapping-rain-water",
    practice_problem_slugs: ["trapping-rain-water"],
    difficulty_tier: 4,
    required: true,
  },
  41: {
    day_number: 41,
    topic_name: "two-pointers",
    primary_problem_slug: "sorted-squares",
    practice_problem_slugs: ["sorted-squares"],
    difficulty_tier: 1,
    required: true,
  },
  42: {
    day_number: 42,
    topic_name: "strings",
    primary_problem_slug: "longest-substring",
    practice_problem_slugs: ["longest-substring"],
    difficulty_tier: 3,
    required: true,
  },
  43: {
    day_number: 43,
    topic_name: "arrays",
    primary_problem_slug: "maximum-average-subarray-i",
    practice_problem_slugs: ["maximum-average-subarray-i"],
    difficulty_tier: 1,
    required: true,
  },
  44: {
    day_number: 44,
    topic_name: "arrays",
    primary_problem_slug: "minimum-size-subarray-sum",
    practice_problem_slugs: ["minimum-size-subarray-sum"],
    difficulty_tier: 2,
    required: true,
  },
  45: {
    day_number: 45,
    topic_name: "hashing",
    primary_problem_slug: "repeated-dna-sequences",
    practice_problem_slugs: ["repeated-dna-sequences"],
    difficulty_tier: 2,
    required: true,
  },
  46: {
    day_number: 46,
    topic_name: "arrays",
    primary_problem_slug: "majority-element",
    practice_problem_slugs: ["majority-element"],
    difficulty_tier: 1,
    required: true,
  },
  47: {
    day_number: 47,
    topic_name: "arrays",
    primary_problem_slug: "rotate-array",
    practice_problem_slugs: ["rotate-array"],
    difficulty_tier: 2,
    required: true,
  },
  48: {
    day_number: 48,
    topic_name: "arrays",
    primary_problem_slug: "find-disappeared",
    practice_problem_slugs: ["find-disappeared"],
    difficulty_tier: 1,
    required: true,
  },
  49: {
    day_number: 49,
    topic_name: "two-pointers",
    primary_problem_slug: "sort-by-parity",
    practice_problem_slugs: ["sort-by-parity"],
    difficulty_tier: 1,
    required: true,
  },
  50: {
    day_number: 50,
    topic_name: "two-pointers",
    primary_problem_slug: "trapping-rain-water",
    practice_problem_slugs: ["trapping-rain-water", "container-most-water"],
    difficulty_tier: 4,
    required: true,
  },
  51: {
    day_number: 51,
    topic_name: "binary-search",
    primary_problem_slug: "binary-search",
    practice_problem_slugs: ["binary-search"],
    difficulty_tier: 1,
    required: true,
  },
  52: {
    day_number: 52,
    topic_name: "binary-search",
    primary_problem_slug: "search-insert-position",
    practice_problem_slugs: ["search-insert-position"],
    difficulty_tier: 1,
    required: true,
  },
  53: {
    day_number: 53,
    topic_name: "binary-search",
    primary_problem_slug: "search-range",
    practice_problem_slugs: ["search-range"],
    difficulty_tier: 2,
    required: true,
  },
  54: {
    day_number: 54,
    topic_name: "binary-search",
    primary_problem_slug: "search-rotated",
    practice_problem_slugs: ["search-rotated"],
    difficulty_tier: 3,
    required: true,
  },
  55: {
    day_number: 55,
    topic_name: "searching-sorting",
    primary_problem_slug: "insertion-sort-list-array",
    practice_problem_slugs: ["insertion-sort-list-array"],
    difficulty_tier: 1,
    required: true,
  },
  56: {
    day_number: 56,
    topic_name: "searching-sorting",
    primary_problem_slug: "sort-an-array",
    practice_problem_slugs: ["sort-an-array"],
    difficulty_tier: 2,
    required: true,
  },
  57: {
    day_number: 57,
    topic_name: "searching-sorting",
    primary_problem_slug: "sort-colors",
    practice_problem_slugs: ["sort-colors"],
    difficulty_tier: 2,
    required: true,
  },
  58: {
    day_number: 58,
    topic_name: "searching-sorting",
    primary_problem_slug: "kth-largest-element-in-an-array",
    practice_problem_slugs: ["kth-largest-element-in-an-array"],
    difficulty_tier: 2,
    required: true,
  },
  59: {
    day_number: 59,
    topic_name: "searching-sorting",
    primary_problem_slug: "relative-sort-array",
    practice_problem_slugs: ["relative-sort-array"],
    difficulty_tier: 1,
    required: true,
  },
  60: {
    day_number: 60,
    topic_name: "searching-sorting",
    primary_problem_slug: "sort-an-array",
    practice_problem_slugs: ["sort-an-array", "relative-sort-array"],
    difficulty_tier: 2,
    required: true,
  },
  61: {
    day_number: 61,
    topic_name: "binary-search",
    primary_problem_slug: "find-min-rotated",
    practice_problem_slugs: ["find-min-rotated"],
    difficulty_tier: 2,
    required: true,
  },
  62: {
    day_number: 62,
    topic_name: "binary-search",
    primary_problem_slug: "find-peak",
    practice_problem_slugs: ["find-peak"],
    difficulty_tier: 2,
    required: true,
  },
  63: {
    day_number: 63,
    topic_name: "binary-search",
    primary_problem_slug: "count-negatives",
    practice_problem_slugs: ["count-negatives"],
    difficulty_tier: 1,
    required: true,
  },
  64: {
    day_number: 64,
    topic_name: "binary-search",
    primary_problem_slug: "koko-bananas",
    practice_problem_slugs: ["koko-bananas"],
    difficulty_tier: 3,
    required: true,
  },
  65: {
    day_number: 65,
    topic_name: "binary-search",
    primary_problem_slug: "median-two-arrays",
    practice_problem_slugs: ["median-two-arrays"],
    difficulty_tier: 4,
    required: true,
  },
  66: {
    day_number: 66,
    topic_name: "hashing",
    primary_problem_slug: "design-hashmap",
    practice_problem_slugs: ["design-hashmap"],
    difficulty_tier: 2,
    required: true,
  },
  67: {
    day_number: 67,
    topic_name: "hashing",
    primary_problem_slug: "group-anagrams",
    practice_problem_slugs: ["group-anagrams"],
    difficulty_tier: 2,
    required: true,
  },
  68: {
    day_number: 68,
    topic_name: "strings",
    primary_problem_slug: "first-unique-char",
    practice_problem_slugs: ["first-unique-char"],
    difficulty_tier: 1,
    required: true,
  },
  69: {
    day_number: 69,
    topic_name: "arrays",
    primary_problem_slug: "subarray-sum-k",
    practice_problem_slugs: ["subarray-sum-k"],
    difficulty_tier: 2,
    required: true,
  },
  70: {
    day_number: 70,
    topic_name: "hashing",
    primary_problem_slug: "longest-consecutive-sequence",
    practice_problem_slugs: ["longest-consecutive-sequence"],
    difficulty_tier: 3,
    required: true,
  },
  71: {
    day_number: 71,
    topic_name: "hashing",
    primary_problem_slug: "insert-delete-getrandom-o1",
    practice_problem_slugs: ["insert-delete-getrandom-o1"],
    difficulty_tier: 3,
    required: true,
  },
  72: {
    day_number: 72,
    topic_name: "hashing",
    primary_problem_slug: "lru-cache",
    practice_problem_slugs: ["lru-cache"],
    difficulty_tier: 3,
    required: true,
  },
  73: {
    day_number: 73,
    topic_name: "strings",
    primary_problem_slug: "longest-palindrome",
    practice_problem_slugs: ["longest-palindrome"],
    difficulty_tier: 1,
    required: true,
  },
  74: {
    day_number: 74,
    topic_name: "strings",
    primary_problem_slug: "count-vowels",
    practice_problem_slugs: ["count-vowels"],
    difficulty_tier: 1,
    required: true,
  },
  75: {
    day_number: 75,
    topic_name: "hashing",
    primary_problem_slug: "longest-consecutive-sequence",
    practice_problem_slugs: ["longest-consecutive-sequence", "lru-cache"],
    difficulty_tier: 3,
    required: true,
  },
  76: {
    day_number: 76,
    topic_name: "two-pointers",
    primary_problem_slug: "reverse-list",
    practice_problem_slugs: ["reverse-list"],
    difficulty_tier: 1,
    required: true,
  },
  77: {
    day_number: 77,
    topic_name: "linked-lists",
    primary_problem_slug: "reverse-linked-list",
    practice_problem_slugs: ["reverse-linked-list"],
    difficulty_tier: 1,
    required: true,
  },
  78: {
    day_number: 78,
    topic_name: "linked-lists",
    primary_problem_slug: "middle-of-the-linked-list",
    practice_problem_slugs: ["middle-of-the-linked-list"],
    difficulty_tier: 1,
    required: true,
  },
  79: {
    day_number: 79,
    topic_name: "linked-lists",
    primary_problem_slug: "merge-two-sorted-linked-lists",
    practice_problem_slugs: ["merge-two-sorted-linked-lists"],
    difficulty_tier: 2,
    required: true,
  },
  80: {
    day_number: 80,
    topic_name: "two-pointers",
    primary_problem_slug: "merge-sorted-lists",
    practice_problem_slugs: ["merge-sorted-lists"],
    difficulty_tier: 1,
    required: true,
  },
  81: {
    day_number: 81,
    topic_name: "linked-lists",
    primary_problem_slug: "linked-list-cycle",
    practice_problem_slugs: ["linked-list-cycle"],
    difficulty_tier: 1,
    required: true,
  },
  82: {
    day_number: 82,
    topic_name: "linked-lists",
    primary_problem_slug: "linked-list-cycle-ii",
    practice_problem_slugs: ["linked-list-cycle-ii"],
    difficulty_tier: 2,
    required: true,
  },
  83: {
    day_number: 83,
    topic_name: "linked-lists",
    primary_problem_slug: "remove-nth-node-from-end",
    practice_problem_slugs: ["remove-nth-node-from-end"],
    difficulty_tier: 2,
    required: true,
  },
  84: {
    day_number: 84,
    topic_name: "linked-lists",
    primary_problem_slug: "remove-linked-list-elements",
    practice_problem_slugs: ["remove-linked-list-elements"],
    difficulty_tier: 1,
    required: true,
  },
  85: {
    day_number: 85,
    topic_name: "linked-lists",
    primary_problem_slug: "reverse-nodes-in-k-group",
    practice_problem_slugs: ["reverse-nodes-in-k-group"],
    difficulty_tier: 4,
    required: true,
  },
  86: {
    day_number: 86,
    topic_name: "stacks",
    primary_problem_slug: "valid-parentheses",
    practice_problem_slugs: ["valid-parentheses"],
    difficulty_tier: 1,
    required: true,
  },
  87: {
    day_number: 87,
    topic_name: "stacks",
    primary_problem_slug: "valid-parentheses",
    practice_problem_slugs: ["valid-parentheses"],
    difficulty_tier: 1,
    required: true,
  },
  88: {
    day_number: 88,
    topic_name: "stacks",
    primary_problem_slug: "min-stack-ops",
    practice_problem_slugs: ["min-stack-ops"],
    difficulty_tier: 1,
    required: true,
  },
  89: {
    day_number: 89,
    topic_name: "stacks",
    primary_problem_slug: "design-circular-queue",
    practice_problem_slugs: ["design-circular-queue"],
    difficulty_tier: 2,
    required: true,
  },
  90: {
    day_number: 90,
    topic_name: "stacks",
    primary_problem_slug: "implement-queue-using-stacks",
    practice_problem_slugs: ["implement-queue-using-stacks"],
    difficulty_tier: 1,
    required: true,
  },
  91: {
    day_number: 91,
    topic_name: "stacks",
    primary_problem_slug: "daily-temperatures",
    practice_problem_slugs: ["daily-temperatures"],
    difficulty_tier: 2,
    required: true,
  },
  92: {
    day_number: 92,
    topic_name: "stacks",
    primary_problem_slug: "asteroid-collision",
    practice_problem_slugs: ["asteroid-collision"],
    difficulty_tier: 2,
    required: true,
  },
  93: {
    day_number: 93,
    topic_name: "stacks",
    primary_problem_slug: "sliding-window-maximum",
    practice_problem_slugs: ["sliding-window-maximum"],
    difficulty_tier: 4,
    required: true,
  },
  94: {
    day_number: 94,
    topic_name: "stacks",
    primary_problem_slug: "eval-rpn",
    practice_problem_slugs: ["eval-rpn"],
    difficulty_tier: 2,
    required: true,
  },
  95: {
    day_number: 95,
    topic_name: "stacks",
    primary_problem_slug: "simplify-path",
    practice_problem_slugs: ["simplify-path"],
    difficulty_tier: 2,
    required: true,
  },
  96: {
    day_number: 96,
    topic_name: "trees",
    primary_problem_slug: "binary-tree-inorder-traversal",
    practice_problem_slugs: ["binary-tree-inorder-traversal"],
    difficulty_tier: 1,
    required: true,
  },
  97: {
    day_number: 97,
    topic_name: "trees",
    primary_problem_slug: "maximum-depth-of-binary-tree",
    practice_problem_slugs: ["maximum-depth-of-binary-tree"],
    difficulty_tier: 1,
    required: true,
  },
  98: {
    day_number: 98,
    topic_name: "trees",
    primary_problem_slug: "invert-binary-tree",
    practice_problem_slugs: ["invert-binary-tree"],
    difficulty_tier: 1,
    required: true,
  },
  99: {
    day_number: 99,
    topic_name: "trees",
    primary_problem_slug: "binary-tree-level-order-traversal",
    practice_problem_slugs: ["binary-tree-level-order-traversal"],
    difficulty_tier: 2,
    required: true,
  },
  100: {
    day_number: 100,
    topic_name: "trees",
    primary_problem_slug: "symmetric-tree",
    practice_problem_slugs: ["symmetric-tree"],
    difficulty_tier: 1,
    required: true,
  },
  101: {
    day_number: 101,
    topic_name: "trees",
    primary_problem_slug: "validate-binary-search-tree",
    practice_problem_slugs: ["validate-binary-search-tree"],
    difficulty_tier: 2,
    required: true,
  },
  102: {
    day_number: 102,
    topic_name: "trees",
    primary_problem_slug: "kth-smallest-element-in-a-bst",
    practice_problem_slugs: ["kth-smallest-element-in-a-bst"],
    difficulty_tier: 2,
    required: true,
  },
  103: {
    day_number: 103,
    topic_name: "trees",
    primary_problem_slug: "lowest-common-ancestor-of-a-binary-tree",
    practice_problem_slugs: ["lowest-common-ancestor-of-a-binary-tree"],
    difficulty_tier: 2,
    required: true,
  },
  104: {
    day_number: 104,
    topic_name: "trees",
    primary_problem_slug: "serialize-and-deserialize-binary-tree",
    practice_problem_slugs: ["serialize-and-deserialize-binary-tree"],
    difficulty_tier: 4,
    required: true,
  },
  105: {
    day_number: 105,
    topic_name: "trees",
    primary_problem_slug: "same-tree",
    practice_problem_slugs: ["same-tree"],
    difficulty_tier: 1,
    required: true,
  },
  106: {
    day_number: 106,
    topic_name: "trees",
    primary_problem_slug: "balanced-binary-tree",
    practice_problem_slugs: ["balanced-binary-tree"],
    difficulty_tier: 2,
    required: true,
  },
  107: {
    day_number: 107,
    topic_name: "trees",
    primary_problem_slug: "lowest-common-ancestor-of-a-bst",
    practice_problem_slugs: ["lowest-common-ancestor-of-a-bst"],
    difficulty_tier: 2,
    required: true,
  },
  108: {
    day_number: 108,
    topic_name: "trees",
    primary_problem_slug: "implement-trie-prefix-tree",
    practice_problem_slugs: ["implement-trie-prefix-tree"],
    difficulty_tier: 2,
    required: true,
  },
  109: {
    day_number: 109,
    topic_name: "trees",
    primary_problem_slug: "design-add-and-search-words",
    practice_problem_slugs: ["design-add-and-search-words"],
    difficulty_tier: 3,
    required: true,
  },
  110: {
    day_number: 110,
    topic_name: "trees",
    primary_problem_slug: "validate-binary-search-tree",
    practice_problem_slugs: ["validate-binary-search-tree", "serialize-and-deserialize-binary-tree"],
    difficulty_tier: 4,
    required: true,
  },
  111: {
    day_number: 111,
    topic_name: "heaps",
    primary_problem_slug: "last-stone-weight",
    practice_problem_slugs: ["last-stone-weight"],
    difficulty_tier: 1,
    required: true,
  },
  112: {
    day_number: 112,
    topic_name: "heaps",
    primary_problem_slug: "kth-largest-element-in-a-stream",
    practice_problem_slugs: ["kth-largest-element-in-a-stream"],
    difficulty_tier: 1,
    required: true,
  },
  113: {
    day_number: 113,
    topic_name: "heaps",
    primary_problem_slug: "k-closest-points-to-origin",
    practice_problem_slugs: ["k-closest-points-to-origin"],
    difficulty_tier: 2,
    required: true,
  },
  114: {
    day_number: 114,
    topic_name: "heaps",
    primary_problem_slug: "top-k-frequent-elements",
    practice_problem_slugs: ["top-k-frequent-elements"],
    difficulty_tier: 2,
    required: true,
  },
  115: {
    day_number: 115,
    topic_name: "heaps",
    primary_problem_slug: "merge-k-sorted-lists",
    practice_problem_slugs: ["merge-k-sorted-lists"],
    difficulty_tier: 3,
    required: true,
  },
  116: {
    day_number: 116,
    topic_name: "heaps",
    primary_problem_slug: "find-median-from-data-stream",
    practice_problem_slugs: ["find-median-from-data-stream"],
    difficulty_tier: 4,
    required: true,
  },
  117: {
    day_number: 117,
    topic_name: "heaps",
    primary_problem_slug: "task-scheduler",
    practice_problem_slugs: ["task-scheduler"],
    difficulty_tier: 3,
    required: true,
  },
  118: {
    day_number: 118,
    topic_name: "heaps",
    primary_problem_slug: "find-k-pairs-with-smallest-sums",
    practice_problem_slugs: ["find-k-pairs-with-smallest-sums"],
    difficulty_tier: 3,
    required: true,
  },
  119: {
    day_number: 119,
    topic_name: "heaps",
    primary_problem_slug: "find-median-from-data-stream",
    practice_problem_slugs: ["find-median-from-data-stream"],
    difficulty_tier: 4,
    required: true,
  },
  120: {
    day_number: 120,
    topic_name: "heaps",
    primary_problem_slug: "merge-k-sorted-lists",
    practice_problem_slugs: ["merge-k-sorted-lists", "find-median-from-data-stream"],
    difficulty_tier: 4,
    required: true,
  },
  121: {
    day_number: 121,
    topic_name: "graphs",
    primary_problem_slug: "find-judge",
    practice_problem_slugs: ["find-judge"],
    difficulty_tier: 1,
    required: true,
  },
  122: {
    day_number: 122,
    topic_name: "graphs",
    primary_problem_slug: "valid-path",
    practice_problem_slugs: ["valid-path"],
    difficulty_tier: 1,
    required: true,
  },
  123: {
    day_number: 123,
    topic_name: "graphs",
    primary_problem_slug: "flood-fill",
    practice_problem_slugs: ["flood-fill"],
    difficulty_tier: 1,
    required: true,
  },
  124: {
    day_number: 124,
    topic_name: "graphs",
    primary_problem_slug: "course-schedule",
    practice_problem_slugs: ["course-schedule"],
    difficulty_tier: 2,
    required: true,
  },
  125: {
    day_number: 125,
    topic_name: "graphs",
    primary_problem_slug: "course-schedule-ii",
    practice_problem_slugs: ["course-schedule-ii"],
    difficulty_tier: 3,
    required: true,
  },
  126: {
    day_number: 126,
    topic_name: "graphs",
    primary_problem_slug: "keys-and-rooms",
    practice_problem_slugs: ["keys-and-rooms"],
    difficulty_tier: 2,
    required: true,
  },
  127: {
    day_number: 127,
    topic_name: "graphs",
    primary_problem_slug: "is-graph-bipartite",
    practice_problem_slugs: ["is-graph-bipartite"],
    difficulty_tier: 2,
    required: true,
  },
  128: {
    day_number: 128,
    topic_name: "graphs",
    primary_problem_slug: "network-delay-time",
    practice_problem_slugs: ["network-delay-time"],
    difficulty_tier: 3,
    required: true,
  },
  129: {
    day_number: 129,
    topic_name: "graphs",
    primary_problem_slug: "cheapest-flights-within-k-stops",
    practice_problem_slugs: ["cheapest-flights-within-k-stops"],
    difficulty_tier: 4,
    required: true,
  },
  130: {
    day_number: 130,
    topic_name: "graphs",
    primary_problem_slug: "redundant-connection",
    practice_problem_slugs: ["redundant-connection"],
    difficulty_tier: 2,
    required: true,
  },
  131: {
    day_number: 131,
    topic_name: "graphs",
    primary_problem_slug: "min-cost-to-connect-all-points",
    practice_problem_slugs: ["min-cost-to-connect-all-points"],
    difficulty_tier: 3,
    required: true,
  },
  132: {
    day_number: 132,
    topic_name: "graphs",
    primary_problem_slug: "min-cost-to-connect-all-points",
    practice_problem_slugs: ["min-cost-to-connect-all-points"],
    difficulty_tier: 3,
    required: true,
  },
  133: {
    day_number: 133,
    topic_name: "graphs",
    primary_problem_slug: "critical-connections-in-a-network",
    practice_problem_slugs: ["critical-connections-in-a-network"],
    difficulty_tier: 4,
    required: true,
  },
  134: {
    day_number: 134,
    topic_name: "graphs",
    primary_problem_slug: "critical-connections-in-a-network",
    practice_problem_slugs: ["critical-connections-in-a-network"],
    difficulty_tier: 4,
    required: true,
  },
  135: {
    day_number: 135,
    topic_name: "graphs",
    primary_problem_slug: "number-of-islands",
    practice_problem_slugs: ["number-of-islands", "network-delay-time"],
    difficulty_tier: 3,
    required: true,
  },
  136: {
    day_number: 136,
    topic_name: "greedy",
    primary_problem_slug: "maximum-units-on-a-truck",
    practice_problem_slugs: ["maximum-units-on-a-truck"],
    difficulty_tier: 1,
    required: true,
  },
  137: {
    day_number: 137,
    topic_name: "greedy",
    primary_problem_slug: "non-overlapping-intervals",
    practice_problem_slugs: ["non-overlapping-intervals"],
    difficulty_tier: 3,
    required: true,
  },
  138: {
    day_number: 138,
    topic_name: "greedy",
    primary_problem_slug: "maximum-units-on-a-truck",
    practice_problem_slugs: ["maximum-units-on-a-truck"],
    difficulty_tier: 1,
    required: true,
  },
  139: {
    day_number: 139,
    topic_name: "greedy",
    primary_problem_slug: "minimum-deletions-to-make-character-frequencies-unique",
    practice_problem_slugs: ["minimum-deletions-to-make-character-frequencies-unique"],
    difficulty_tier: 2,
    required: true,
  },
  140: {
    day_number: 140,
    topic_name: "greedy",
    primary_problem_slug: "jump-game",
    practice_problem_slugs: ["jump-game"],
    difficulty_tier: 2,
    required: true,
  },
  141: {
    day_number: 141,
    topic_name: "greedy",
    primary_problem_slug: "partition-labels",
    practice_problem_slugs: ["partition-labels"],
    difficulty_tier: 2,
    required: true,
  },
  142: {
    day_number: 142,
    topic_name: "greedy",
    primary_problem_slug: "gas-station",
    practice_problem_slugs: ["gas-station"],
    difficulty_tier: 3,
    required: true,
  },
  143: {
    day_number: 143,
    topic_name: "greedy",
    primary_problem_slug: "candy",
    practice_problem_slugs: ["candy"],
    difficulty_tier: 4,
    required: true,
  },
  144: {
    day_number: 144,
    topic_name: "greedy",
    primary_problem_slug: "jump-game-ii",
    practice_problem_slugs: ["jump-game-ii"],
    difficulty_tier: 3,
    required: true,
  },
  145: {
    day_number: 145,
    topic_name: "greedy",
    primary_problem_slug: "candy",
    practice_problem_slugs: ["candy", "gas-station"],
    difficulty_tier: 4,
    required: true,
  },
  146: {
    day_number: 146,
    topic_name: "dynamic-programming",
    primary_problem_slug: "climbing-stairs",
    practice_problem_slugs: ["climbing-stairs"],
    difficulty_tier: 1,
    required: true,
  },
  147: {
    day_number: 147,
    topic_name: "dynamic-programming",
    primary_problem_slug: "house-robber",
    practice_problem_slugs: ["house-robber"],
    difficulty_tier: 2,
    required: true,
  },
  148: {
    day_number: 148,
    topic_name: "dynamic-programming",
    primary_problem_slug: "unique-paths",
    practice_problem_slugs: ["unique-paths"],
    difficulty_tier: 2,
    required: true,
  },
  149: {
    day_number: 149,
    topic_name: "dynamic-programming",
    primary_problem_slug: "partition-equal-subset-sum",
    practice_problem_slugs: ["partition-equal-subset-sum"],
    difficulty_tier: 3,
    required: true,
  },
  150: {
    day_number: 150,
    topic_name: "dynamic-programming",
    primary_problem_slug: "coin-change",
    practice_problem_slugs: ["coin-change"],
    difficulty_tier: 2,
    required: true,
  },
  151: {
    day_number: 151,
    topic_name: "dynamic-programming",
    primary_problem_slug: "longest-increasing-subsequence",
    practice_problem_slugs: ["longest-increasing-subsequence"],
    difficulty_tier: 3,
    required: true,
  },
  152: {
    day_number: 152,
    topic_name: "dynamic-programming",
    primary_problem_slug: "longest-common-subsequence",
    practice_problem_slugs: ["longest-common-subsequence"],
    difficulty_tier: 3,
    required: true,
  },
  153: {
    day_number: 153,
    topic_name: "dynamic-programming",
    primary_problem_slug: "edit-distance",
    practice_problem_slugs: ["edit-distance"],
    difficulty_tier: 4,
    required: true,
  },
  154: {
    day_number: 154,
    topic_name: "dynamic-programming",
    primary_problem_slug: "coin-change-ii",
    practice_problem_slugs: ["coin-change-ii"],
    difficulty_tier: 3,
    required: true,
  },
  155: {
    day_number: 155,
    topic_name: "dynamic-programming",
    primary_problem_slug: "minimum-path-sum",
    practice_problem_slugs: ["minimum-path-sum"],
    difficulty_tier: 2,
    required: true,
  },
  156: {
    day_number: 156,
    topic_name: "bit-manipulation",
    primary_problem_slug: "number-of-1-bits",
    practice_problem_slugs: ["number-of-1-bits"],
    difficulty_tier: 1,
    required: true,
  },
  157: {
    day_number: 157,
    topic_name: "advanced-dsa",
    primary_problem_slug: "n-queens",
    practice_problem_slugs: ["n-queens"],
    difficulty_tier: 4,
    required: true,
  },
  158: {
    day_number: 158,
    topic_name: "advanced-dsa",
    primary_problem_slug: "range-sum-query-mutable",
    practice_problem_slugs: ["range-sum-query-mutable"],
    difficulty_tier: 4,
    required: true,
  },
  159: {
    day_number: 159,
    topic_name: "advanced-dsa",
    primary_problem_slug: "word-search-ii",
    practice_problem_slugs: ["word-search-ii"],
    difficulty_tier: 4,
    required: true,
  },
  160: {
    day_number: 160,
    topic_name: "advanced-dsa",
    primary_problem_slug: "lfu-cache",
    practice_problem_slugs: ["lfu-cache", "n-queens", "word-search-ii"],
    difficulty_tier: 5,
    required: true,
  },
};

export function getPracticeForDay(dayNumber: number): CurriculumPracticeMapping | null {
  return CURRICULUM_PRACTICE_MAP[dayNumber] ?? null;
}
