"""Seed topics and problems.

Idempotent: re-running upserts by slug rather than duplicating.

Inventory note: the PRD's Phase 1 asks for 40-60 problems while BUILD_PROMPTS
asks for 12. This seeds 18 (3 per topic, tiers 1-5). That is enough to
demonstrate adaptive difficulty, but /api/problems/next widens its tier search
when a tier is empty precisely because 18 problems cannot fill 6 topics x 5
tiers. Add problems before claiming the adaptive engine is fully exercised.

Run:  python -m app.seed
"""

from __future__ import annotations

import uuid

from sqlalchemy import select

from app.database import SessionLocal
from app.models.models import Problem, Topic

TOPICS = [
    ("arrays", "Arrays & Hashing"),
    ("two-pointers", "Two Pointers"),
    ("strings", "Strings"),
    ("stacks", "Stacks & Queues"),
    ("binary-search", "Binary Search"),
    ("graphs", "Graphs & Trees"),
]


def P(slug, title, topic, tier, entry, statement, constraints,
      opt_t, opt_s, starter, cases):
    return {
        "slug": slug, "title": title, "topic": topic, "difficulty_tier": tier,
        "entry_point": entry, "statement_md": statement, "constraints_md": constraints,
        "optimal_time": opt_t, "optimal_space": opt_s,
        "starter_code": {"python": starter}, "test_cases": cases,
    }


PROBLEMS = [
    # --- arrays -----------------------------------------------------------
    P("contains-duplicate", "Contains Duplicate", "arrays", 1, "contains_duplicate",
      "Given an integer array `nums`, return `true` if any value appears at least twice.",
      "- `0 <= len(nums) <= 10^5`\n- `-10^9 <= nums[i] <= 10^9`", "O(n)", "O(n)",
      "def contains_duplicate(nums):\n    pass\n",
      [{"args": [[1, 2, 3, 1]], "expected": True},
       {"args": [[1, 2, 3, 4]], "expected": False},
       {"args": [[]], "expected": False},
       {"args": [[7]], "expected": False},
       {"args": [[0, 0]], "expected": True},
       {"args": [[-1, -1, 5]], "expected": True}]),

    P("two-sum", "Two Sum", "arrays", 2, "two_sum",
      "Given `nums` and `target`, return indices of the two numbers summing to "
      "`target`. Return `[]` if none exist.",
      "- Exactly one valid answer when one exists\n- `0 <= len(nums) <= 10^4`",
      "O(n)", "O(n)",
      "def two_sum(nums, target):\n    pass\n",
      [{"args": [[2, 7, 11, 15], 9], "expected": [0, 1]},
       {"args": [[3, 2, 4], 6], "expected": [1, 2]},
       {"args": [[3, 3], 6], "expected": [0, 1]},
       {"args": [[], 0], "expected": []},
       {"args": [[1], 1], "expected": []},
       {"args": [[-3, 4, 3, 90], 0], "expected": [0, 2]}]),

    P("product-except-self", "Product of Array Except Self", "arrays", 4,
      "product_except_self",
      "Return an array where `out[i]` is the product of all elements except "
      "`nums[i]`. Do it without division.",
      "- `1 <= len(nums) <= 10^5`\n- Products fit in 32 bits", "O(n)", "O(1)",
      "def product_except_self(nums):\n    pass\n",
      [{"args": [[1, 2, 3, 4]], "expected": [24, 12, 8, 6]},
       {"args": [[-1, 1, 0, -3, 3]], "expected": [0, 0, 9, 0, 0]},
       {"args": [[1, 1]], "expected": [1, 1]},
       {"args": [[5]], "expected": [1]},
       {"args": [[0, 0]], "expected": [0, 0]},
       {"args": [[2, 3, 4, 5]], "expected": [60, 40, 30, 24]}]),

    # --- two pointers -----------------------------------------------------
    P("reverse-list", "Reverse a List", "two-pointers", 1, "reverse_list",
      "Reverse a list in place and return it.",
      "- `0 <= len(items) <= 10^5`", "O(n)", "O(1)",
      "def reverse_list(items):\n    pass\n",
      [{"args": [[1, 2, 3]], "expected": [3, 2, 1]},
       {"args": [[]], "expected": []},
       {"args": [[1]], "expected": [1]},
       {"args": [[1, 2]], "expected": [2, 1]},
       {"args": [[5, 5, 5]], "expected": [5, 5, 5]}]),

    P("valid-palindrome", "Valid Palindrome", "two-pointers", 2, "is_palindrome",
      "Return `true` if `s` is a palindrome, considering only alphanumeric "
      "characters and ignoring case.",
      "- `0 <= len(s) <= 2 * 10^5`", "O(n)", "O(1)",
      "def is_palindrome(s):\n    pass\n",
      [{"args": ["A man, a plan, a canal: Panama"], "expected": True},
       {"args": ["race a car"], "expected": False},
       {"args": [""], "expected": True},
       {"args": [" "], "expected": True},
       {"args": ["ab_a"], "expected": True},
       {"args": ["0P"], "expected": False}]),

    P("container-most-water", "Container With Most Water", "two-pointers", 4,
      "max_area",
      "Given heights, find two lines forming a container holding the most water.",
      "- `2 <= len(height) <= 10^5`", "O(n)", "O(1)",
      "def max_area(height):\n    pass\n",
      [{"args": [[1, 8, 6, 2, 5, 4, 8, 3, 7]], "expected": 49},
       {"args": [[1, 1]], "expected": 1},
       {"args": [[4, 3, 2, 1, 4]], "expected": 16},
       {"args": [[1, 2, 1]], "expected": 2},
       {"args": [[0, 0]], "expected": 0},
       {"args": [[2, 3, 4, 5, 18, 17, 6]], "expected": 17}]),

    # --- strings ----------------------------------------------------------
    P("count-vowels", "Count Vowels", "strings", 1, "count_vowels",
      "Return the number of vowels (a, e, i, o, u, case-insensitive) in `s`.",
      "- `0 <= len(s) <= 10^5`", "O(n)", "O(1)",
      "def count_vowels(s):\n    pass\n",
      [{"args": ["hello"], "expected": 2},
       {"args": [""], "expected": 0},
       {"args": ["xyz"], "expected": 0},
       {"args": ["AEIOU"], "expected": 5},
       {"args": ["aAeE"], "expected": 4}]),

    P("valid-anagram", "Valid Anagram", "strings", 2, "is_anagram",
      "Return `true` if `t` is an anagram of `s`.",
      "- `0 <= len(s), len(t) <= 5 * 10^4`\n- Lowercase English letters",
      "O(n)", "O(1)",
      "def is_anagram(s, t):\n    pass\n",
      [{"args": ["anagram", "nagaram"], "expected": True},
       {"args": ["rat", "car"], "expected": False},
       {"args": ["", ""], "expected": True},
       {"args": ["a", "ab"], "expected": False},
       {"args": ["aacc", "ccac"], "expected": False},
       {"args": ["ab", "ba"], "expected": True}]),

    P("longest-substring", "Longest Substring Without Repeating Characters",
      "strings", 4, "length_of_longest_substring",
      "Return the length of the longest substring without repeating characters.",
      "- `0 <= len(s) <= 5 * 10^4`", "O(n)", "O(min(n, m))",
      "def length_of_longest_substring(s):\n    pass\n",
      [{"args": ["abcabcbb"], "expected": 3},
       {"args": ["bbbbb"], "expected": 1},
       {"args": ["pwwkew"], "expected": 3},
       {"args": [""], "expected": 0},
       {"args": [" "], "expected": 1},
       {"args": ["dvdf"], "expected": 3}]),

    # --- stacks -----------------------------------------------------------
    P("valid-parentheses", "Valid Parentheses", "stacks", 2, "is_valid",
      "Given a string of brackets, determine if the input is valid.",
      "- `0 <= len(s) <= 10^4`", "O(n)", "O(n)",
      "def is_valid(s):\n    pass\n",
      [{"args": ["()"], "expected": True},
       {"args": ["()[]{}"], "expected": True},
       {"args": ["(]"], "expected": False},
       {"args": [""], "expected": True},
       {"args": ["("], "expected": False},
       {"args": ["]"], "expected": False}]),

    P("min-stack-ops", "Minimum After Operations", "stacks", 3, "min_after_ops",
      "Process a list of ops: an integer pushes, `'C'` cancels the last, "
      "`'D'` pushes double the last, `'+'` pushes the sum of the last two. "
      "Return the final total.",
      "- `1 <= len(ops) <= 1000`", "O(n)", "O(n)",
      "def min_after_ops(ops):\n    pass\n",
      [{"args": [[5, 2, "C", "D", "+"]], "expected": 30},
       {"args": [[5, -2, 4, "C", "D", 9, "+", "+"]], "expected": 27},
       {"args": [[1]], "expected": 1},
       {"args": [[1, "C"]], "expected": 0},
       {"args": [[3, "D"]], "expected": 9}]),

    P("daily-temperatures", "Daily Temperatures", "stacks", 4, "daily_temperatures",
      "For each day, how many days until a warmer temperature? 0 if none.",
      "- `1 <= len(temps) <= 10^5`", "O(n)", "O(n)",
      "def daily_temperatures(temps):\n    pass\n",
      [{"args": [[73, 74, 75, 71, 69, 72, 76, 73]],
        "expected": [1, 1, 4, 2, 1, 1, 0, 0]},
       {"args": [[30, 40, 50, 60]], "expected": [1, 1, 1, 0]},
       {"args": [[30, 60, 90]], "expected": [1, 1, 0]},
       {"args": [[50]], "expected": [0]},
       {"args": [[50, 50, 50]], "expected": [0, 0, 0]}]),

    # --- binary search ----------------------------------------------------
    P("binary-search", "Binary Search", "binary-search", 1, "search",
      "Return the index of `target` in a sorted array, or -1.",
      "- `0 <= len(nums) <= 10^4`\n- `nums` is sorted ascending", "O(log n)", "O(1)",
      "def search(nums, target):\n    pass\n",
      [{"args": [[-1, 0, 3, 5, 9, 12], 9], "expected": 4},
       {"args": [[-1, 0, 3, 5, 9, 12], 2], "expected": -1},
       {"args": [[], 1], "expected": -1},
       {"args": [[5], 5], "expected": 0},
       {"args": [[5], 1], "expected": -1},
       {"args": [[1, 2], 2], "expected": 1}]),

    P("search-rotated", "Search in Rotated Sorted Array", "binary-search", 4,
      "search_rotated",
      "Search `target` in a rotated sorted array in O(log n). Return index or -1.",
      "- `1 <= len(nums) <= 5000`\n- All values distinct", "O(log n)", "O(1)",
      "def search_rotated(nums, target):\n    pass\n",
      [{"args": [[4, 5, 6, 7, 0, 1, 2], 0], "expected": 4},
       {"args": [[4, 5, 6, 7, 0, 1, 2], 3], "expected": -1},
       {"args": [[1], 0], "expected": -1},
       {"args": [[1], 1], "expected": 0},
       {"args": [[3, 1], 1], "expected": 1},
       {"args": [[5, 1, 3], 3], "expected": 2}]),

    P("median-two-arrays", "Median of Two Sorted Arrays", "binary-search", 5,
      "find_median",
      "Return the median of two sorted arrays in O(log(m+n)).",
      "- `0 <= m + n <= 2000`\n- Not concatenate-and-sort", "O(log(m+n))", "O(1)",
      "def find_median(a, b):\n    pass\n",
      [{"args": [[1, 3], [2]], "expected": 2.0},
       {"args": [[1, 2], [3, 4]], "expected": 2.5},
       {"args": [[], [1]], "expected": 1.0},
       {"args": [[2], []], "expected": 2.0},
       {"args": [[0, 0], [0, 0]], "expected": 0.0},
       {"args": [[1, 1, 3], [2]], "expected": 1.5}]),

    # --- graphs / trees ---------------------------------------------------
    P("max-depth", "Maximum Depth of Nested List", "graphs", 2, "max_depth",
      "Given a nested list, return its maximum nesting depth. `[]` has depth 1.",
      "- Nesting depth `<= 100`", "O(n)", "O(d)",
      "def max_depth(items):\n    pass\n",
      [{"args": [[1, 2, 3]], "expected": 1},
       {"args": [[1, [2, [3]]]], "expected": 3},
       {"args": [[]], "expected": 1},
       {"args": [[[], []]], "expected": 2},
       {"args": [[[[[1]]]]], "expected": 4}]),

    P("number-of-islands", "Number of Islands", "graphs", 4, "num_islands",
      "Count islands in a grid of `'1'` (land) and `'0'` (water). "
      "Islands connect 4-directionally.",
      "- `0 <= rows, cols <= 300`", "O(m*n)", "O(m*n)",
      "def num_islands(grid):\n    pass\n",
      [{"args": [[["1", "1", "0"], ["1", "0", "0"], ["0", "0", "1"]]], "expected": 2},
       {"args": [[["1", "1"], ["1", "1"]]], "expected": 1},
       {"args": [[]], "expected": 0},
       {"args": [[["0"]]], "expected": 0},
       {"args": [[["1"]]], "expected": 1},
       {"args": [[["1", "0", "1"], ["0", "0", "0"], ["1", "0", "1"]]], "expected": 4}]),

    P("course-schedule", "Course Schedule", "graphs", 5, "can_finish",
      "Given `n` courses and prerequisite pairs `[a, b]` (take `b` before `a`), "
      "return whether all courses can be finished.",
      "- `1 <= n <= 2000`\n- Detect cycles", "O(V+E)", "O(V+E)",
      "def can_finish(n, prerequisites):\n    pass\n",
      [{"args": [2, [[1, 0]]], "expected": True},
       {"args": [2, [[1, 0], [0, 1]]], "expected": False},
       {"args": [1, []], "expected": True},
       {"args": [3, [[1, 0], [2, 1]]], "expected": True},
       {"args": [3, [[0, 1], [1, 2], [2, 0]]], "expected": False},
       {"args": [4, [[1, 0], [2, 0], [3, 1], [3, 2]]], "expected": True}]),

    # --- arrays (added) ---
    P('running-sum', 'Running Sum of 1d Array', 'arrays', 1, 'running_sum',
      'Return the running sum where `out[i] = nums[0] + ... + nums[i]`.',
      '- `1 <= len(nums) <= 1000`', 'O(n)', 'O(1)',
      'def running_sum(nums):\n    pass\n',
      [{"args": [[1, 2, 3, 4]], "expected": [1, 3, 6, 10]},
       {"args": [[1, 1, 1, 1]], "expected": [1, 2, 3, 4]},
       {"args": [[3, 1, 2, 10, 1]], "expected": [3, 4, 6, 16, 17]},
       {"args": [[5]], "expected": [5]},
       {"args": [[-1, 2, -3]], "expected": [-1, 1, -2]}]),

    P('max-consecutive-ones', 'Max Consecutive Ones', 'arrays', 1, 'find_max_consecutive_ones',
      'Given a binary array `nums`, return the maximum number of consecutive 1s.',
      '- `1 <= len(nums) <= 10^5`\n- `nums[i]` is 0 or 1', 'O(n)', 'O(1)',
      'def find_max_consecutive_ones(nums):\n    pass\n',
      [{"args": [[1, 1, 0, 1, 1, 1]], "expected": 3},
       {"args": [[1, 0, 1, 1, 0, 1]], "expected": 2},
       {"args": [[0]], "expected": 0},
       {"args": [[1]], "expected": 1},
       {"args": [[0, 0, 0]], "expected": 0}]),

    P('single-number', 'Single Number', 'arrays', 2, 'single_number',
      'Every element appears twice except one. Find the one that appears once.',
      '- `1 <= len(nums) <= 3*10^4`\n- Each element appears twice but one', 'O(n)', 'O(1)',
      'def single_number(nums):\n    pass\n',
      [{"args": [[2, 2, 1]], "expected": 1},
       {"args": [[4, 1, 2, 1, 2]], "expected": 4},
       {"args": [[1]], "expected": 1},
       {"args": [[7, 3, 3]], "expected": 7},
       {"args": [[0, 5, 0]], "expected": 5}]),

    P('move-zeroes', 'Move Zeroes', 'arrays', 2, 'move_zeroes',
      'Move all 0s to the end while keeping the relative order of non-zero elements. Return the resulting list.',
      '- `1 <= len(nums) <= 10^4`', 'O(n)', 'O(1)',
      'def move_zeroes(nums):\n    pass\n',
      [{"args": [[0, 1, 0, 3, 12]], "expected": [1, 3, 12, 0, 0]},
       {"args": [[0]], "expected": [0]},
       {"args": [[1, 2, 3]], "expected": [1, 2, 3]},
       {"args": [[0, 0, 1]], "expected": [1, 0, 0]},
       {"args": [[1, 0, 2, 0, 3]], "expected": [1, 2, 3, 0, 0]}]),

    P('majority-element', 'Majority Element', 'arrays', 3, 'majority_element',
      'Return the element that appears more than `len(nums)//2` times. You may assume it always exists.',
      '- `1 <= len(nums) <= 5*10^4`', 'O(n)', 'O(1)',
      'def majority_element(nums):\n    pass\n',
      [{"args": [[3, 2, 3]], "expected": 3},
       {"args": [[2, 2, 1, 1, 1, 2, 2]], "expected": 2},
       {"args": [[1]], "expected": 1},
       {"args": [[5, 5, 5, 1, 2]], "expected": 5},
       {"args": [[6, 6, 6, 6]], "expected": 6}]),

    P('max-subarray', 'Maximum Subarray', 'arrays', 3, 'max_sub_array',
      'Return the largest sum of any contiguous subarray (at least one element).',
      '- `1 <= len(nums) <= 10^5`', 'O(n)', 'O(1)',
      'def max_sub_array(nums):\n    pass\n',
      [{"args": [[-2, 1, -3, 4, -1, 2, 1, -5, 4]], "expected": 6},
       {"args": [[1]], "expected": 1},
       {"args": [[5, 4, -1, 7, 8]], "expected": 23},
       {"args": [[-1, -2, -3]], "expected": -1},
       {"args": [[-5]], "expected": -5}]),

    P('find-disappeared', 'Find All Numbers Disappeared in an Array', 'arrays', 3, 'find_disappeared_numbers',
      '`nums` holds values in `[1, n]` where `n = len(nums)`. Return, in ascending order, all values in `[1, n]` that do not appear.',
      '- `1 <= len(nums) <= 10^5`\n- `1 <= nums[i] <= n`', 'O(n)', 'O(1)',
      'def find_disappeared_numbers(nums):\n    pass\n',
      [{"args": [[4, 3, 2, 7, 8, 2, 3, 1]], "expected": [5, 6]},
       {"args": [[1, 1]], "expected": [2]},
       {"args": [[1]], "expected": []},
       {"args": [[2, 2]], "expected": [1]},
       {"args": [[1, 2, 3, 4]], "expected": []}]),

    P('rotate-array', 'Rotate Array', 'arrays', 3, 'rotate',
      'Rotate the list to the right by `k` steps and return it.',
      '- `1 <= len(nums) <= 10^5`\n- `0 <= k <= 10^5`', 'O(n)', 'O(1)',
      'def rotate(nums, k):\n    pass\n',
      [{"args": [[1, 2, 3, 4, 5, 6, 7], 3], "expected": [5, 6, 7, 1, 2, 3, 4]},
       {"args": [[-1, -100, 3, 99], 2], "expected": [3, 99, -1, -100]},
       {"args": [[1], 0], "expected": [1]},
       {"args": [[1, 2], 3], "expected": [2, 1]},
       {"args": [[1, 2, 3], 0], "expected": [1, 2, 3]}]),

    P('subarray-sum-k', 'Subarray Sum Equals K', 'arrays', 4, 'subarray_sum',
      'Return the number of contiguous subarrays whose sum equals `k`.',
      '- `1 <= len(nums) <= 2*10^4`\n- `-1000 <= nums[i] <= 1000`', 'O(n)', 'O(n)',
      'def subarray_sum(nums, k):\n    pass\n',
      [{"args": [[1, 1, 1], 2], "expected": 2},
       {"args": [[1, 2, 3], 3], "expected": 2},
       {"args": [[1], 0], "expected": 0},
       {"args": [[-1, -1, 1], 0], "expected": 1},
       {"args": [[3, 4, 7, 2, -3, 1, 4, 2], 7], "expected": 4}]),

    # --- two-pointers (added) ---
    P('is-subsequence', 'Is Subsequence', 'two-pointers', 1, 'is_subsequence',
      'Return `true` if `s` is a subsequence of `t`.',
      '- `0 <= len(s) <= 100`\n- `0 <= len(t) <= 10^4`', 'O(n)', 'O(1)',
      'def is_subsequence(s, t):\n    pass\n',
      [{"args": ['abc', 'ahbgdc'], "expected": True},
       {"args": ['axc', 'ahbgdc'], "expected": False},
       {"args": ['', 'abc'], "expected": True},
       {"args": ['abc', ''], "expected": False},
       {"args": ['ace', 'abcde'], "expected": True}]),

    P('sorted-squares', 'Squares of a Sorted Array', 'two-pointers', 2, 'sorted_squares',
      'Given a sorted array, return the squares of each number sorted ascending.',
      '- `1 <= len(nums) <= 10^4`\n- `nums` sorted ascending', 'O(n)', 'O(n)',
      'def sorted_squares(nums):\n    pass\n',
      [{"args": [[-4, -1, 0, 3, 10]], "expected": [0, 1, 9, 16, 100]},
       {"args": [[-7, -3, 2, 3, 11]], "expected": [4, 9, 9, 49, 121]},
       {"args": [[1]], "expected": [1]},
       {"args": [[-2]], "expected": [4]},
       {"args": [[-5, -3, -1]], "expected": [1, 9, 25]}]),

    P('two-sum-sorted', 'Two Sum II - Input Array Is Sorted', 'two-pointers', 2, 'two_sum_sorted',
      'Given a 1-indexed sorted array, return the 1-based indices of the two numbers adding to `target`. Exactly one solution exists.',
      '- `2 <= len(nums) <= 3*10^4`\n- `nums` sorted ascending', 'O(n)', 'O(1)',
      'def two_sum_sorted(nums, target):\n    pass\n',
      [{"args": [[2, 7, 11, 15], 9], "expected": [1, 2]},
       {"args": [[2, 3, 4], 6], "expected": [1, 3]},
       {"args": [[-1, 0], -1], "expected": [1, 2]},
       {"args": [[1, 2, 3, 4], 7], "expected": [3, 4]},
       {"args": [[5, 25, 75], 100], "expected": [2, 3]}]),

    P('sort-by-parity', 'Sort Array By Parity', 'two-pointers', 2, 'sort_array_by_parity',
      'Return an array with all even elements first (any order among evens is fine, but keep evens in their original relative order), then the odds in original relative order.',
      '- `1 <= len(nums) <= 5000`', 'O(n)', 'O(n)',
      'def sort_array_by_parity(nums):\n    pass\n',
      [{"args": [[3, 1, 2, 4]], "expected": [2, 4, 3, 1]},
       {"args": [[0]], "expected": [0]},
       {"args": [[1, 3, 5]], "expected": [1, 3, 5]},
       {"args": [[2, 4, 6]], "expected": [2, 4, 6]},
       {"args": [[7, 2, 5, 8]], "expected": [2, 8, 7, 5]}]),

    P('dedupe-sorted', 'Remove Duplicates from Sorted Array', 'two-pointers', 2, 'dedupe_sorted',
      'Given a sorted array, return the list of unique values in ascending order.',
      '- `0 <= len(nums) <= 3*10^4`\n- `nums` sorted ascending', 'O(n)', 'O(1)',
      'def dedupe_sorted(nums):\n    pass\n',
      [{"args": [[1, 1, 2]], "expected": [1, 2]},
       {"args": [[0, 0, 1, 1, 1, 2, 2, 3, 3, 4]], "expected": [0, 1, 2, 3, 4]},
       {"args": [[]], "expected": []},
       {"args": [[5]], "expected": [5]},
       {"args": [[1, 2, 3]], "expected": [1, 2, 3]}]),

    P('merge-sorted-lists', 'Merge Two Sorted Lists', 'two-pointers', 2, 'merge_sorted',
      'Merge two ascending-sorted lists into one ascending-sorted list.',
      '- `0 <= len(a), len(b) <= 10^4`', 'O(n+m)', 'O(n+m)',
      'def merge_sorted(a, b):\n    pass\n',
      [{"args": [[1, 2, 4], [1, 3, 4]], "expected": [1, 1, 2, 3, 4, 4]},
       {"args": [[], []], "expected": []},
       {"args": [[], [0]], "expected": [0]},
       {"args": [[1], [2]], "expected": [1, 2]},
       {"args": [[1, 5, 9], [2, 3, 10]], "expected": [1, 2, 3, 5, 9, 10]}]),

    P('three-sum', '3Sum', 'two-pointers', 4, 'three_sum',
      'Return all unique triplets `[a, b, c]` that sum to 0, each triplet sorted ascending, and the list of triplets sorted ascending.',
      '- `3 <= len(nums) <= 3000`', 'O(n^2)', 'O(1)',
      'def three_sum(nums):\n    pass\n',
      [{"args": [[-1, 0, 1, 2, -1, -4]], "expected": [[-1, -1, 2], [-1, 0, 1]]},
       {"args": [[0, 1, 1]], "expected": []},
       {"args": [[0, 0, 0]], "expected": [[0, 0, 0]]},
       {"args": [[-2, 0, 1, 1, 2]], "expected": [[-2, 0, 2], [-2, 1, 1]]},
       {"args": [[1, 2, -3]], "expected": [[-3, 1, 2]]}]),

    P('trapping-rain-water', 'Trapping Rain Water', 'two-pointers', 5, 'trap',
      'Given bar heights, compute how much rain water can be trapped.',
      '- `1 <= len(height) <= 2*10^4`', 'O(n)', 'O(1)',
      'def trap(height):\n    pass\n',
      [{"args": [[0, 1, 0, 2, 1, 0, 1, 3, 2, 1, 2, 1]], "expected": 6},
       {"args": [[4, 2, 0, 3, 2, 5]], "expected": 9},
       {"args": [[1, 2, 3]], "expected": 0},
       {"args": [[3, 2, 1]], "expected": 0},
       {"args": [[5]], "expected": 0}]),

    # --- strings (added) ---
    P('reverse-string', 'Reverse String', 'strings', 1, 'reverse_string',
      'Return the string reversed.',
      '- `0 <= len(s) <= 10^5`', 'O(n)', 'O(n)',
      'def reverse_string(s):\n    pass\n',
      [{"args": ['hello'], "expected": 'olleh'},
       {"args": [''], "expected": ''},
       {"args": ['a'], "expected": 'a'},
       {"args": ['ab'], "expected": 'ba'},
       {"args": ['racecar'], "expected": 'racecar'}]),

    P('fizzbuzz', 'Fizz Buzz', 'strings', 1, 'fizz_buzz',
      "Return a list of length `n` (1-indexed): `'FizzBuzz'` if divisible by 15, `'Fizz'` by 3, `'Buzz'` by 5, else the number as a string.",
      '- `1 <= n <= 10^4`', 'O(n)', 'O(n)',
      'def fizz_buzz(n):\n    pass\n',
      [{"args": [3], "expected": ['1', '2', 'Fizz']},
       {"args": [5], "expected": ['1', '2', 'Fizz', '4', 'Buzz']},
       {"args": [15], "expected": ['1', '2', 'Fizz', '4', 'Buzz', 'Fizz', '7', '8', 'Fizz', 'Buzz', '11', 'Fizz', '13', '14', 'FizzBuzz']},
       {"args": [1], "expected": ['1']},
       {"args": [16], "expected": ['1', '2', 'Fizz', '4', 'Buzz', 'Fizz', '7', '8', 'Fizz', 'Buzz', '11', 'Fizz', '13', '14', 'FizzBuzz', '16']}]),

    P('first-unique-char', 'First Unique Character in a String', 'strings', 2, 'first_uniq_char',
      'Return the index of the first non-repeating character, or -1 if none.',
      '- `1 <= len(s) <= 10^5`\n- lowercase English letters', 'O(n)', 'O(1)',
      'def first_uniq_char(s):\n    pass\n',
      [{"args": ['leetcode'], "expected": 0},
       {"args": ['loveleetcode'], "expected": 2},
       {"args": ['aabb'], "expected": -1},
       {"args": ['z'], "expected": 0},
       {"args": ['abcabd'], "expected": 2}]),

    P('longest-common-prefix', 'Longest Common Prefix', 'strings', 2, 'longest_common_prefix',
      "Return the longest common prefix among a list of strings, or `''`.",
      '- `1 <= len(strs) <= 200`', 'O(n*m)', 'O(1)',
      'def longest_common_prefix(strs):\n    pass\n',
      [{"args": [['flower', 'flow', 'flight']], "expected": 'fl'},
       {"args": [['dog', 'racecar', 'car']], "expected": ''},
       {"args": [['interspecies', 'interstellar', 'interstate']], "expected": 'inters'},
       {"args": [['a']], "expected": 'a'},
       {"args": [['abc', 'abc', 'abc']], "expected": 'abc'}]),

    P('reverse-words', 'Reverse Words in a String', 'strings', 2, 'reverse_words',
      'Return the words of `s` in reverse order, single-spaced, with leading, trailing and repeated spaces removed.',
      '- `1 <= len(s) <= 10^4`', 'O(n)', 'O(n)',
      'def reverse_words(s):\n    pass\n',
      [{"args": ['the sky is blue'], "expected": 'blue is sky the'},
       {"args": ['  hello world  '], "expected": 'world hello'},
       {"args": ['a good   example'], "expected": 'example good a'},
       {"args": ['single'], "expected": 'single'},
       {"args": ['  leading'], "expected": 'leading'}]),

    P('longest-palindrome', 'Longest Palindrome', 'strings', 2, 'longest_palindrome',
      'Given a string of letters, return the length of the longest palindrome that can be built using those letters (case-sensitive).',
      '- `1 <= len(s) <= 2000`', 'O(n)', 'O(1)',
      'def longest_palindrome(s):\n    pass\n',
      [{"args": ['abccccdd'], "expected": 7},
       {"args": ['a'], "expected": 1},
       {"args": ['bb'], "expected": 2},
       {"args": ['abc'], "expected": 1},
       {"args": ['Aa'], "expected": 1}]),

    P('roman-to-int', 'Roman to Integer', 'strings', 3, 'roman_to_int',
      'Convert a Roman numeral string to an integer.',
      '- `1 <= len(s) <= 15`\n- valid Roman numeral in `[1, 3999]`', 'O(n)', 'O(1)',
      'def roman_to_int(s):\n    pass\n',
      [{"args": ['III'], "expected": 3},
       {"args": ['LVIII'], "expected": 58},
       {"args": ['MCMXCIV'], "expected": 1994},
       {"args": ['IV'], "expected": 4},
       {"args": ['IX'], "expected": 9}]),

    P('valid-palindrome-ii', 'Valid Palindrome II', 'strings', 3, 'valid_palindrome_ii',
      'Return `true` if `s` can be a palindrome after deleting at most one character.',
      '- `1 <= len(s) <= 10^5`\n- lowercase English letters', 'O(n)', 'O(1)',
      'def valid_palindrome_ii(s):\n    pass\n',
      [{"args": ['aba'], "expected": True},
       {"args": ['abca'], "expected": True},
       {"args": ['abc'], "expected": False},
       {"args": ['a'], "expected": True},
       {"args": ['deeee'], "expected": True}]),

    P('add-binary', 'Add Binary', 'strings', 2, 'add_binary',
      'Given two binary strings `a` and `b`, return their sum as a binary string.',
      '- `1 <= len(a), len(b) <= 10^4`', 'O(n)', 'O(n)',
      'def add_binary(a, b):\n    pass\n',
      [{"args": ['11', '1'], "expected": '100'},
       {"args": ['1010', '1011'], "expected": '10101'},
       {"args": ['0', '0'], "expected": '0'},
       {"args": ['1', '111'], "expected": '1000'},
       {"args": ['100', '110010'], "expected": '110110'}]),

    # --- stacks (added) ---
    P('backspace-compare', 'Backspace String Compare', 'stacks', 2, 'backspace_compare',
      "Two strings contain letters and `'#'` (backspace). Return `true` if they are equal after applying backspaces.",
      '- `1 <= len(s), len(t) <= 200`', 'O(n)', 'O(n)',
      'def backspace_compare(s, t):\n    pass\n',
      [{"args": ['ab#c', 'ad#c'], "expected": True},
       {"args": ['ab##', 'c#d#'], "expected": True},
       {"args": ['a#c', 'b'], "expected": False},
       {"args": ['xywrrmp', 'xywrrmu#p'], "expected": True},
       {"args": ['bxj##tw', 'bxo#j##tw'], "expected": True}]),

    P('remove-adjacent-dupes', 'Remove All Adjacent Duplicates In String', 'stacks', 2, 'remove_adjacent_duplicates',
      'Repeatedly remove two adjacent equal letters until none remain. Return the final string.',
      '- `1 <= len(s) <= 10^5`\n- lowercase English letters', 'O(n)', 'O(n)',
      'def remove_adjacent_duplicates(s):\n    pass\n',
      [{"args": ['abbaca'], "expected": 'ca'},
       {"args": ['azxxzy'], "expected": 'ay'},
       {"args": ['aaaa'], "expected": ''},
       {"args": ['abc'], "expected": 'abc'},
       {"args": ['a'], "expected": 'a'}]),

    P('make-good', 'Make The String Great', 'stacks', 2, 'make_good',
      "Remove adjacent pairs of the same letter in different cases (e.g. `'aA'` or `'Aa'`) repeatedly. Return the resulting string.",
      '- `1 <= len(s) <= 100`', 'O(n)', 'O(n)',
      'def make_good(s):\n    pass\n',
      [{"args": ['leEeetcode'], "expected": 'leetcode'},
       {"args": ['abBAcC'], "expected": ''},
       {"args": ['s'], "expected": 's'},
       {"args": ['Pp'], "expected": ''},
       {"args": ['mC'], "expected": 'mC'}]),

    P('eval-rpn', 'Evaluate Reverse Polish Notation', 'stacks', 3, 'eval_rpn',
      'Evaluate an arithmetic expression in Reverse Polish Notation. Operators are `+ - * /`; division truncates toward zero. Tokens are a list of strings.',
      '- `1 <= len(tokens) <= 10^4`', 'O(n)', 'O(n)',
      'def eval_rpn(tokens):\n    pass\n',
      [{"args": [['2', '1', '+', '3', '*']], "expected": 9},
       {"args": [['4', '13', '5', '/', '+']], "expected": 6},
       {"args": [['10', '6', '9', '3', '+', '-11', '*', '/', '*', '17', '+', '5', '+']], "expected": 22},
       {"args": [['3', '4', '-']], "expected": -1},
       {"args": [['5']], "expected": 5}]),

    P('simplify-path', 'Simplify Path', 'stacks', 3, 'simplify_path',
      'Given a Unix-style absolute path, return its canonical form.',
      '- `1 <= len(path) <= 3000`\n- path starts with `/`', 'O(n)', 'O(n)',
      'def simplify_path(path):\n    pass\n',
      [{"args": ['/home/'], "expected": '/home'},
       {"args": ['/../'], "expected": '/'},
       {"args": ['/home//foo/'], "expected": '/home/foo'},
       {"args": ['/a/./b/../../c/'], "expected": '/c'},
       {"args": ['/'], "expected": '/'}]),

    P('decode-string', 'Decode String', 'stacks', 4, 'decode_string',
      'Decode a string encoded as `k[encoded]`, meaning `encoded` repeated `k` times. Encodings may nest.',
      '- `1 <= len(s) <= 30`\n- well-formed input', 'O(n)', 'O(n)',
      'def decode_string(s):\n    pass\n',
      [{"args": ['3[a]2[bc]'], "expected": 'aaabcbc'},
       {"args": ['3[a2[c]]'], "expected": 'accaccacc'},
       {"args": ['2[abc]3[cd]ef'], "expected": 'abcabccdcdcdef'},
       {"args": ['1[x]'], "expected": 'x'},
       {"args": ['abc'], "expected": 'abc'}]),

    P('asteroid-collision', 'Asteroid Collision', 'stacks', 4, 'asteroid_collision',
      'Each asteroid moves right (positive) or left (negative) at the same speed. When two collide the smaller explodes; equal sizes both explode. Return the surviving asteroids.',
      '- `1 <= len(asteroids) <= 10^4`\n- `asteroids[i] != 0`', 'O(n)', 'O(n)',
      'def asteroid_collision(asteroids):\n    pass\n',
      [{"args": [[5, 10, -5]], "expected": [5, 10]},
       {"args": [[8, -8]], "expected": []},
       {"args": [[10, 2, -5]], "expected": [10]},
       {"args": [[-2, -1, 1, 2]], "expected": [-2, -1, 1, 2]},
       {"args": [[1, 2, 3]], "expected": [1, 2, 3]}]),

    P('largest-rectangle', 'Largest Rectangle in Histogram', 'stacks', 5, 'largest_rectangle_area',
      'Given bar heights of width 1, return the area of the largest rectangle.',
      '- `1 <= len(heights) <= 10^5`', 'O(n)', 'O(n)',
      'def largest_rectangle_area(heights):\n    pass\n',
      [{"args": [[2, 1, 5, 6, 2, 3]], "expected": 10},
       {"args": [[2, 4]], "expected": 4},
       {"args": [[1]], "expected": 1},
       {"args": [[5, 5, 5]], "expected": 15},
       {"args": [[6, 2, 5, 4, 5, 1, 6]], "expected": 12}]),

    # --- binary-search (added) ---
    P('search-insert', 'Search Insert Position', 'binary-search', 2, 'search_insert',
      'Return the index where `target` is, or where it would be inserted to keep the sorted array sorted.',
      '- `1 <= len(nums) <= 10^4`\n- `nums` sorted, distinct', 'O(log n)', 'O(1)',
      'def search_insert(nums, target):\n    pass\n',
      [{"args": [[1, 3, 5, 6], 5], "expected": 2},
       {"args": [[1, 3, 5, 6], 2], "expected": 1},
       {"args": [[1, 3, 5, 6], 7], "expected": 4},
       {"args": [[1, 3, 5, 6], 0], "expected": 0},
       {"args": [[1], 0], "expected": 0}]),

    P('my-sqrt', 'Sqrt(x)', 'binary-search', 2, 'my_sqrt',
      'Return the integer square root of `x` (floor of the true square root).',
      '- `0 <= x <= 2^31 - 1`', 'O(log x)', 'O(1)',
      'def my_sqrt(x):\n    pass\n',
      [{"args": [4], "expected": 2},
       {"args": [8], "expected": 2},
       {"args": [0], "expected": 0},
       {"args": [1], "expected": 1},
       {"args": [2147395600], "expected": 46340}]),

    P('arrange-coins', 'Arranging Coins', 'binary-search', 2, 'arrange_coins',
      'You build a staircase where row `i` needs `i` coins. Given `n` coins, return the number of complete rows.',
      '- `1 <= n <= 2^31 - 1`', 'O(log n)', 'O(1)',
      'def arrange_coins(n):\n    pass\n',
      [{"args": [5], "expected": 2},
       {"args": [8], "expected": 3},
       {"args": [1], "expected": 1},
       {"args": [3], "expected": 2},
       {"args": [1804289383], "expected": 60070}]),

    P('count-negatives', 'Count Negative Numbers in a Sorted Matrix', 'binary-search', 2, 'count_negatives',
      'Given a matrix sorted non-increasing row-wise and column-wise, return the count of negative numbers.',
      '- `1 <= rows, cols <= 100`', 'O(m+n)', 'O(1)',
      'def count_negatives(grid):\n    pass\n',
      [{"args": [[[4, 3, 2, -1], [3, 2, 1, -1], [1, 1, -1, -2], [-1, -1, -2, -3]]], "expected": 8},
       {"args": [[[3, 2], [1, 0]]], "expected": 0},
       {"args": [[[-1]]], "expected": 1},
       {"args": [[[1, -1], [-1, -1]]], "expected": 3},
       {"args": [[[5, 1, 0]]], "expected": 0}]),

    P('find-min-rotated', 'Find Minimum in Rotated Sorted Array', 'binary-search', 3, 'find_min',
      'Return the minimum of a rotated ascending sorted array of distinct values.',
      '- `1 <= len(nums) <= 5000`\n- distinct values', 'O(log n)', 'O(1)',
      'def find_min(nums):\n    pass\n',
      [{"args": [[3, 4, 5, 1, 2]], "expected": 1},
       {"args": [[4, 5, 6, 7, 0, 1, 2]], "expected": 0},
       {"args": [[11, 13, 15, 17]], "expected": 11},
       {"args": [[2, 1]], "expected": 1},
       {"args": [[1]], "expected": 1}]),

    P('find-peak', 'Find Peak Element', 'binary-search', 3, 'find_peak_element',
      'A peak is strictly greater than its neighbors (out-of-bounds counts as -inf). Return the index of any peak.',
      '- `1 <= len(nums) <= 1000`\n- `nums[i] != nums[i+1]`', 'O(log n)', 'O(1)',
      'def find_peak_element(nums):\n    pass\n',
      [{"args": [[1, 2, 3, 1]], "expected": 2},
       {"args": [[1, 3, 5, 6, 4, 2, 0]], "expected": 3},
       {"args": [[1]], "expected": 0},
       {"args": [[1, 2]], "expected": 1},
       {"args": [[2, 1]], "expected": 0}]),

    P('search-range', 'Find First and Last Position', 'binary-search', 4, 'search_range',
      'Return `[first, last]` indices of `target` in a sorted array, or `[-1, -1]`.',
      '- `0 <= len(nums) <= 10^5`\n- `nums` sorted ascending', 'O(log n)', 'O(1)',
      'def search_range(nums, target):\n    pass\n',
      [{"args": [[5, 7, 7, 8, 8, 10], 8], "expected": [3, 4]},
       {"args": [[5, 7, 7, 8, 8, 10], 6], "expected": [-1, -1]},
       {"args": [[], 0], "expected": [-1, -1]},
       {"args": [[1], 1], "expected": [0, 0]},
       {"args": [[2, 2, 2], 2], "expected": [0, 2]}]),

    P('single-non-duplicate', 'Single Element in a Sorted Array', 'binary-search', 4, 'single_non_duplicate',
      'Every element appears exactly twice except one that appears once, in a sorted array. Return that single element.',
      '- `1 <= len(nums) <= 10^5`', 'O(log n)', 'O(1)',
      'def single_non_duplicate(nums):\n    pass\n',
      [{"args": [[1, 1, 2, 3, 3, 4, 4, 8, 8]], "expected": 2},
       {"args": [[3, 3, 7, 7, 10, 11, 11]], "expected": 10},
       {"args": [[1]], "expected": 1},
       {"args": [[1, 1, 2]], "expected": 2},
       {"args": [[0, 0, 1, 1, 2, 2, 3]], "expected": 3}]),

    P('koko-bananas', 'Koko Eating Bananas', 'binary-search', 4, 'min_eating_speed',
      'Piles of bananas and `h` hours. Each hour Koko eats up to `k` bananas from one pile. Return the minimum integer `k` to finish all piles within `h` hours.',
      '- `1 <= len(piles) <= 10^4`\n- `len(piles) <= h <= 10^9`', 'O(n log m)', 'O(1)',
      'def min_eating_speed(piles, h):\n    pass\n',
      [{"args": [[3, 6, 7, 11], 8], "expected": 4},
       {"args": [[30, 11, 23, 4, 20], 5], "expected": 30},
       {"args": [[30, 11, 23, 4, 20], 6], "expected": 23},
       {"args": [[1], 1], "expected": 1},
       {"args": [[1000000000], 2], "expected": 500000000}]),

    # --- graphs (added) ---
    P('find-center', 'Find Center of Star Graph', 'graphs', 1, 'find_center',
      'In a star graph of `n` nodes given as edges, return the center node.',
      '- `3 <= n`\n- input is a valid star graph', 'O(1)', 'O(1)',
      'def find_center(edges):\n    pass\n',
      [{"args": [[[1, 2], [2, 3], [4, 2]]], "expected": 2},
       {"args": [[[1, 2], [5, 1], [1, 3], [1, 4]]], "expected": 1},
       {"args": [[[2, 1], [3, 1]]], "expected": 1},
       {"args": [[[1, 3], [2, 3], [3, 4]]], "expected": 3},
       {"args": [[[4, 1], [4, 2]]], "expected": 4}]),

    P('find-judge', 'Find the Town Judge', 'graphs', 2, 'find_judge',
      "Among `n` people (1..n), the judge trusts nobody and is trusted by everyone else. `trust[i] = [a, b]` means a trusts b. Return the judge's label or -1.",
      '- `1 <= n <= 1000`', 'O(n+e)', 'O(n)',
      'def find_judge(n, trust):\n    pass\n',
      [{"args": [2, [[1, 2]]], "expected": 2},
       {"args": [3, [[1, 3], [2, 3]]], "expected": 3},
       {"args": [3, [[1, 3], [2, 3], [3, 1]]], "expected": -1},
       {"args": [1, []], "expected": 1},
       {"args": [4, [[1, 3], [1, 4], [2, 3], [2, 4], [4, 3]]], "expected": 3}]),

    P('island-perimeter', 'Island Perimeter', 'graphs', 2, 'island_perimeter',
      'Given a grid of 0 (water) and 1 (land) with exactly one island, return its perimeter.',
      '- `1 <= rows, cols <= 100`', 'O(m*n)', 'O(1)',
      'def island_perimeter(grid):\n    pass\n',
      [{"args": [[[0, 1, 0, 0], [1, 1, 1, 0], [0, 1, 0, 0], [1, 1, 0, 0]]], "expected": 16},
       {"args": [[[1]]], "expected": 4},
       {"args": [[[1, 1]]], "expected": 6},
       {"args": [[[1, 0]]], "expected": 4},
       {"args": [[[1, 1], [1, 1]]], "expected": 8}]),

    P('flood-fill', 'Flood Fill', 'graphs', 3, 'flood_fill',
      'Starting at pixel `(sr, sc)`, change its color and all 4-directionally connected pixels of the same original color to `color`. Return the grid.',
      '- `1 <= rows, cols <= 50`', 'O(m*n)', 'O(m*n)',
      'def flood_fill(image, sr, sc, color):\n    pass\n',
      [{"args": [[[1, 1, 1], [1, 1, 0], [1, 0, 1]], 1, 1, 2], "expected": [[2, 2, 2], [2, 2, 0], [2, 0, 1]]},
       {"args": [[[0, 0, 0], [0, 0, 0]], 0, 0, 0], "expected": [[0, 0, 0], [0, 0, 0]]},
       {"args": [[[1]], 0, 0, 2], "expected": [[2]]},
       {"args": [[[0, 0, 0], [0, 1, 1]], 1, 1, 1], "expected": [[0, 0, 0], [0, 1, 1]]},
       {"args": [[[1, 2], [3, 4]], 0, 0, 5], "expected": [[5, 2], [3, 4]]}]),

    P('keys-and-rooms', 'Keys and Rooms', 'graphs', 3, 'can_visit_all_rooms',
      '`rooms[i]` is a list of keys (room numbers) found in room `i`. Starting in room 0, return `true` if you can visit every room.',
      '- `1 <= len(rooms) <= 1000`', 'O(n+e)', 'O(n)',
      'def can_visit_all_rooms(rooms):\n    pass\n',
      [{"args": [[[1], [2], [3], []]], "expected": True},
       {"args": [[[1, 3], [3, 0, 1], [2], [0]]], "expected": False},
       {"args": [[[]]], "expected": True},
       {"args": [[[1], [], [3], []]], "expected": False},
       {"args": [[[2, 3], [], [1], []]], "expected": True}]),

    P('valid-path', 'Find if Path Exists in Graph', 'graphs', 3, 'valid_path',
      'Given `n` nodes (0..n-1) and undirected `edges`, return `true` if there is a path between `source` and `destination`.',
      '- `1 <= n <= 2*10^5`', 'O(n+e)', 'O(n)',
      'def valid_path(n, edges, source, destination):\n    pass\n',
      [{"args": [3, [[0, 1], [1, 2], [2, 0]], 0, 2], "expected": True},
       {"args": [6, [[0, 1], [0, 2], [3, 5], [5, 4], [4, 3]], 0, 5], "expected": False},
       {"args": [1, [], 0, 0], "expected": True},
       {"args": [4, [[0, 1], [1, 2]], 0, 3], "expected": False},
       {"args": [5, [[0, 4]], 0, 4], "expected": True}]),

    P('count-components', 'Number of Connected Components', 'graphs', 4, 'count_components',
      'Given `n` nodes (0..n-1) and undirected `edges`, return the number of connected components.',
      '- `1 <= n <= 2000`', 'O(n+e)', 'O(n)',
      'def count_components(n, edges):\n    pass\n',
      [{"args": [5, [[0, 1], [1, 2], [3, 4]]], "expected": 2},
       {"args": [5, [[0, 1], [1, 2], [2, 3], [3, 4]]], "expected": 1},
       {"args": [4, []], "expected": 4},
       {"args": [1, []], "expected": 1},
       {"args": [6, [[0, 1], [2, 3], [4, 5]]], "expected": 3}]),

    P('max-area-island', 'Max Area of Island', 'graphs', 4, 'max_area_of_island',
      'Return the area of the largest 4-directionally connected island of 1s in a grid of 0s and 1s. 0 if none.',
      '- `1 <= rows, cols <= 50`', 'O(m*n)', 'O(m*n)',
      'def max_area_of_island(grid):\n    pass\n',
      [{"args": [[[0, 0, 1, 0, 0], [0, 0, 0, 0, 0], [0, 1, 1, 0, 0], [0, 1, 0, 0, 0]]], "expected": 3},
       {"args": [[[0, 0, 0], [0, 0, 0]]], "expected": 0},
       {"args": [[[1]]], "expected": 1},
       {"args": [[[1, 1], [1, 1]]], "expected": 4},
       {"args": [[[1, 0, 1], [0, 0, 0], [1, 1, 1]]], "expected": 3}]),

    P('rotting-oranges', 'Rotting Oranges', 'graphs', 4, 'oranges_rotting',
      'Grid cells: 0 empty, 1 fresh, 2 rotten. Each minute a rotten orange rots its 4-directional fresh neighbors. Return minutes until none are fresh, or -1 if impossible.',
      '- `1 <= rows, cols <= 10`', 'O(m*n)', 'O(m*n)',
      'def oranges_rotting(grid):\n    pass\n',
      [{"args": [[[2, 1, 1], [1, 1, 0], [0, 1, 1]]], "expected": 4},
       {"args": [[[2, 1, 1], [0, 1, 1], [1, 0, 1]]], "expected": -1},
       {"args": [[[0, 2]]], "expected": 0},
       {"args": [[[1]]], "expected": -1},
       {"args": [[[2, 2], [1, 1]]], "expected": 1}]),
]


def seed() -> None:
    db = SessionLocal()
    try:
        topic_ids: dict[str, uuid.UUID] = {}
        for slug, name in TOPICS:
            topic = db.execute(select(Topic).where(Topic.slug == slug)).scalars().first()
            if topic is None:
                topic = Topic(id=uuid.uuid4(), slug=slug, name=name)
                db.add(topic)
                db.flush()
            topic_ids[slug] = topic.id

        created = updated = 0
        for spec in PROBLEMS:
            data = dict(spec)
            topic_slug = data.pop("topic")
            existing = db.execute(
                select(Problem).where(Problem.slug == data["slug"])
            ).scalars().first()

            if existing is None:
                db.add(Problem(id=uuid.uuid4(), topic_id=topic_ids[topic_slug], **data))
                created += 1
            else:
                for key, value in data.items():
                    setattr(existing, key, value)
                existing.topic_id = topic_ids[topic_slug]
                updated += 1

        db.commit()
        tiers = sorted({p["difficulty_tier"] for p in PROBLEMS})
        print(f"seeded {len(TOPICS)} topics, {created} new / {updated} updated problems")
        print(f"tiers present: {tiers}")
    finally:
        db.close()


if __name__ == "__main__":
    seed()
