"""
Generates the complete 160-day curriculum metadata manifest (scratch/curriculum_160.json)
and synchronizes frontend/lib/curriculum/curriculumData.ts.
"""

import json
import re

SECTIONS_SPEC = [
    {
        "id": "python-foundations",
        "section_number": 1,
        "title": "Python Foundations",
        "tagline": "Core syntax, data types, execution model, and control structures",
        "day_start": 1,
        "day_end": 10,
        "icon": "Terminal",
    },
    {
        "id": "python-core",
        "section_number": 2,
        "title": "Python Core & Data Structures",
        "tagline": "Containers, iteration protocols, generator streams, OOP, and memory models",
        "day_start": 11,
        "day_end": 25,
        "icon": "Code",
    },
    {
        "id": "computational-thinking",
        "section_number": 3,
        "title": "Problem Solving & Computational Thinking",
        "tagline": "Asymptotic analysis, call stacks, recursion models, invariants, and complexity",
        "day_start": 26,
        "day_end": 35,
        "icon": "Cpu",
    },
    {
        "id": "arrays-and-strings",
        "section_number": 4,
        "title": "Arrays & Strings",
        "tagline": "Prefix sums, difference arrays, two pointers, sliding windows, and linear sweeps",
        "day_start": 36,
        "day_end": 50,
        "icon": "Layers",
    },
    {
        "id": "searching-and-sorting",
        "section_number": 5,
        "title": "Searching & Sorting Algorithms",
        "tagline": "Binary search boundaries, divide and conquer, Timsort, and non-comparison sorting",
        "day_start": 51,
        "day_end": 65,
        "icon": "Search",
    },
    {
        "id": "hashing-and-hash-tables",
        "section_number": 6,
        "title": "Hashing & Hash Tables",
        "tagline": "Collision resolution, frequency mapping, prefix hash maps, and caching architectures",
        "day_start": 66,
        "day_end": 75,
        "icon": "Hash",
    },
    {
        "id": "linked-lists",
        "section_number": 7,
        "title": "Linked Lists",
        "tagline": "Node pointers, sentinel dummies, in-place reversals, fast/slow runners, and cycles",
        "day_start": 76,
        "day_end": 85,
        "icon": "GitCommit",
    },
    {
        "id": "stacks-and-queues",
        "section_number": 8,
        "title": "Stacks & Queues",
        "tagline": "LIFO/FIFO mechanics, monotonic stacks, sliding window max, and parsing machines",
        "day_start": 86,
        "day_end": 95,
        "icon": "Minimize2",
    },
    {
        "id": "trees-and-bst",
        "section_number": 9,
        "title": "Trees & Binary Search Trees",
        "tagline": "Hierarchical DFS/BFS, BST invariants, LCA, Morris traversal, AVL rotations, and tries",
        "day_start": 96,
        "day_end": 110,
        "icon": "GitBranch",
    },
    {
        "id": "heaps-and-priority-queues",
        "section_number": 10,
        "title": "Heaps & Priority Queues",
        "tagline": "Binary heap arrays, sift-up/down, heapq tie-breakers, streaming medians, and scheduling",
        "day_start": 111,
        "day_end": 120,
        "icon": "TrendingUp",
    },
    {
        "id": "graphs",
        "section_number": 11,
        "title": "Graphs & Graph Algorithms",
        "tagline": "Adjacency lists, BFS/DFS, topological sort, Dijkstra, DSU, MST, and bridges/SCCs",
        "day_start": 121,
        "day_end": 135,
        "icon": "Share2",
    },
    {
        "id": "greedy-algorithms",
        "section_number": 12,
        "title": "Greedy Algorithms",
        "tagline": "Greedy-choice proofs, interval scheduling, reachability frontiers, and two-pass greedy",
        "day_start": 136,
        "day_end": 145,
        "icon": "Zap",
    },
    {
        "id": "dynamic-programming",
        "section_number": 13,
        "title": "Dynamic Programming",
        "tagline": "State formulation, 1D/2D grid DP, knapsack variations, LIS, LCS, and interval DP",
        "day_start": 146,
        "day_end": 155,
        "icon": "Grid",
    },
    {
        "id": "advanced-dsa",
        "section_number": 14,
        "title": "Advanced DSA & Interview Mastery",
        "tagline": "Bit manipulation, state-space backtracking, segment trees, system design, and capstone",
        "day_start": 156,
        "day_end": 160,
        "icon": "Award",
    },
]

# Raw 160-day roadmap definitions
DAYS_DATA = [
    # Sec 1 (1-10)
    (1, "python-foundations", "Variables, Expressions & Memory Model", "Python Syntax", 30, "BEGINNER", [], "tier2", "tracing",
     ["Dynamic Typing", "Object References", "Memory Model", "id() & type()"],
     ["Trace variable assignment as name tags bound to heap objects using id()", "Differentiate between value equality (==) and object identity (is)"],
     "Explore dynamic typing, object references, the id() built-in, and Python's memory assignment semantics."),
    (2, "python-foundations", "Numerical Types, Arithmetic & Bitwise", "Numeric System", 25, "BEGINNER", [1], "tier2", "guided",
     ["Integers & Floats", "Floor Division & Modulo", "Bitwise Operators"],
     ["Calculate floor division and modulo on negative numbers using the mathematical floor invariant", "Apply bitwise operators (&, |, ^, ~, <<, >>) and bit_count() to integer flags"],
     "Deep dive into arbitrary-precision integers, IEEE-754 floating point quirks, modulo arithmetic, floor division, and bitwise operators."),
    (3, "python-foundations", "Strings, Slicing & Character Encoding", "String Processing", 30, "BEGINNER", [2], "tier1", "completion",
     ["String Immutability", "Slice Notation [start:stop:step]", "ASCII & ord()/chr()"],
     ["Apply slice notation to extract and reverse strings without modifying the original sequence", "Convert characters to ASCII values using ord() and chr() for array indexing"],
     "Master string immutability, slice notation [start:stop:step], f-strings, and character code conversion using ord() and chr()."),
    (4, "python-foundations", "Booleans & Logical Control Flow", "Conditionals", 25, "BEGINNER", [2], "tier1", "debugging",
     ["Truthiness & Falsy Values", "Short-Circuit Evaluation"],
     ["Predict short-circuit logical evaluation order to prevent unintended side-effects", "Debug conditional branching relying on truthy and falsy object coercion"],
     "Understand truthiness, boolean coercion, short-circuit logical evaluation, and conditional branch structures."),
    (5, "python-foundations", "Loops & Iteration Semantics", "Loop Constructs", 35, "BEGINNER", [4], "tier2", "guided",
     ["for & while Loops", "break, continue & for-else"],
     ["Construct nested loops with break, continue, and the search-and-confirm for-else construct", "Trace range() lazy evaluation across positive and negative strides"],
     "Implement while and for-in loops, loop control statements (break, continue), and the for-else construct."),
    (6, "python-foundations", "Functions, Stack Frames & LEGB Scope", "Function Basics", 30, "BEGINNER", [5], "tier1", "tracing",
     ["Function Signatures & Return", "LEGB Scope & Call Stack"],
     ["Trace variable resolution order across Local, Enclosing, Global, and Built-in scopes", "Analyze call stack activation records and lifetime of local variables"],
     "Define reusable procedures, return contracts, local vs global scope, and the LEGB namespace lookup rule."),
    (7, "python-foundations", "Function Signatures & Default Argument Trap", "Advanced Parameters", 35, "BEGINNER", [6], "tier2", "debugging",
     ["*args & **kwargs", "Mutable Default Argument Trap"],
     ["Debug the shared mutable default argument pitfall using the None sentinel pattern", "Design flexible function signatures using variadic positional and keyword arguments"],
     "Inspect positional and keyword arguments, variadic *args/**kwargs, and the classic mutable default argument trap."),
    (8, "python-foundations", "Basic I/O & Robust Type Casting", "Input / Output", 25, "BEGINNER", [6], "tier1", "guided",
     ["sys.stdin & input()", "Type Casting & Defensive Parsing"],
     ["Parse token streams from standard input with try-except fallback casting", "Format console and string output using format specifiers and sys.stdout.write"],
     "Process standard input safely, parse structured tokens, handle EOF errors, and cast input data."),
    (9, "python-foundations", "Python Standard Library Essentials", "Standard Library", 30, "BEGINNER", [8], "tier1", "completion",
     ["math & sys Modules", "Built-in Iteration Helpers (zip, enumerate)"],
     ["Utilize math functions and sys parameters for algorithmic utility", "Iterate sequences cleanly using enumerate, zip, any, and all"],
     "Leverage standard modules including math, sys, random, and string for algorithmic utility."),
    (10, "python-foundations", "Foundations Check & Synthetic Practice", "Foundations Milestone", 40, "BEGINNER", [1, 2, 3, 4, 5, 6, 7, 8, 9], "tier3", "milestone",
     ["Decomposition", "Input Parsing Pipeline", "Algorithmic Control Flow"],
     ["Synthesize control flow, functional decomposition, and input parsing into a complete script", "Evaluate time and space characteristics of basic algorithmic procedures"],
     "Synthesize variables, conditionals, loops, and functional decomposition to build self-contained algorithmic scripts."),

    # Sec 2 (11-25)
    (11, "python-core", "Lists: Memory Layout & Dynamic Resizing", "List Architecture", 35, "FOUNDATIONAL", [10], "tier2", "guided",
     ["Contiguous Pointer Array", "Amortized O(1) Append vs O(N) Shift"],
     ["Explain CPython list over-allocation formula and dynamic resizing mechanism", "Contrast amortized O(1) append against O(N) cost of insert(0) and pop(0)"],
     "Analyze dynamic array memory layouts, pointer arrays in CPython, amortized O(1) append, and the O(N) insert/pop(0) penalty."),
    (12, "python-core", "List Slicing O(K) Cost & Mutability Traps", "List Mutations", 30, "FOUNDATIONAL", [11], "tier2", "debugging",
     ["Slicing O(K) Time & Space", "Shallow vs Deep Copy"],
     ["Analyze the hidden O(K) time and space allocation cost of list slicing", "Debug reference alias bugs in nested list initialization and shallow copying"],
     "Analyze the O(K) time and space complexity of list slicing, shallow vs deep copies, and in-place list mutations."),
    (13, "python-core", "List Comprehensions & Expressions", "Comprehensions", 25, "FOUNDATIONAL", [12], "tier1", "completion",
     ["List Comprehension Syntax", "Nested Comprehensions & Scoping"],
     ["Construct concise list comprehensions with conditional filtering and mapping", "Flatten and transform 2D matrices using nested comprehension expressions"],
     "Transform data expressively and efficiently using list comprehensions and conditional filters."),
    (14, "python-core", "Tuples, Immutability & The Tuple Swap Idiom", "Tuples", 25, "FOUNDATIONAL", [12], "tier1", "completion",
     ["Tuple Immutability", "Tuple Packing/Unpacking & Swap"],
     ["Explain Python's stack-based variable swap idiom (a, b = b, a) via anonymous tuples", "Utilize immutable tuples as composite hashable keys for grid and graph coordinate lookups"],
     "Understand tuple immutability, memory savings over lists, unpacking idioms, and using tuples as hashable coordinate keys."),
    (15, "python-core", "Dictionaries: Compact Hash Table Internals", "Hash Maps", 35, "FOUNDATIONAL", [14], "tier2", "tracing",
     ["Compact Hash Table Architecture", "Open Addressing & Load Factor"],
     ["Trace dictionary key hashing, index mapping, and perturb-based collision resolution", "Explain the 2/3 load factor resize boundary and requirement for hashable immutable keys"],
     "Explore CPython's compact dictionary architecture, hash functions, open-addressing collision resolution, and average O(1) lookups."),
    (16, "python-core", "Dictionary Methods, Views & Aggregation", "Dictionary Operations", 30, "FOUNDATIONAL", [15], "tier1", "guided",
     ["setdefault() & get()", "Dynamic Dictionary Views & Merge"],
     ["Build aggregation and grouping pipelines using setdefault and dictionary comprehensions", "Manipulate key, value, and item views without allocating intermediate lists"],
     "Apply get(), setdefault(), dictionary views (.keys(), .values(), .items()), and modern dictionary merging."),
    (17, "python-core", "Sets: Value-Free Hash Tables & O(1) Lookups", "Set Theory", 30, "FOUNDATIONAL", [15], "tier1", "problem",
     ["Set O(1) Lookups", "Mathematical Set Operations"],
     ["Eliminate duplicate elements and perform membership tests in O(1) average time", "Execute set union, intersection, and difference operations meeting asymptotic bounds"],
     "Use sets for O(1) membership testing, deduplication, set algebra, and understand the immutable frozenset."),
    (18, "python-core", "The Collections Module: Deque & Counter", "Specialized Containers", 35, "FOUNDATIONAL", [16, 17], "tier2", "guided",
     ["collections.deque O(1) Endpoints", "Counter & defaultdict"],
     ["Implement O(1) double-ended queues using collections.deque, avoiding list pop(0) penalties", "Count element frequencies and build adjacency groupings using Counter and defaultdict"],
     "Master collections.deque for O(1) appends and pops on both ends, defaultdict, and Counter."),
    (19, "python-core", "Iterators & The Iteration Protocol", "Iteration Architecture", 30, "FOUNDATIONAL", [18], "tier2", "algorithm",
     ["__iter__ & __next__ Protocol", "StopIteration & Exhaustion"],
     ["Implement a custom stateful iterator class conforming to the Python iteration protocol", "Handle StopIteration termination and consumable stream invariants"],
     "Understand iterable vs iterator, the __iter__ and __next__ protocols, and consumable stream behavior."),
    (20, "python-core", "Generators & Lazy Memory Streaming", "Lazy Evaluation", 35, "FOUNDATIONAL", [19], "tier2", "algorithm",
     ["yield State Suspension", "yield from & O(1) Space Streams"],
     ["Construct generator functions that yield values incrementally in O(1) auxiliary memory", "Delegate sub-generator execution cleanly using yield from"],
     "Implement generator functions with yield, understand execution suspension, generator expressions, and pipeline composition."),
    (21, "python-core", "Decorators, Closures & Metadata Wrappers", "Higher-Order Functions", 35, "FOUNDATIONAL", [20], "tier2", "debugging",
     ["Closures & Cell Objects", "functools.wraps Decorators"],
     ["Construct function decorators that intercept calls and preserve docstring metadata with functools.wraps", "Debug variable binding bugs in nested function closures"],
     "Write function decorators, understand closures, cell objects, and preserving function metadata with functools.wraps."),
    (22, "python-core", "OOP Classes, Dunder Protocols & __lt__", "Object-Oriented Python", 40, "FOUNDATIONAL", [21], "tier2", "algorithm",
     ["Class Construction & __init__", "Dunders: __repr__, __eq__, __hash__, __lt__"],
     ["Implement custom classes with __repr__, __eq__, and __hash__ contracts", "Define the __lt__ dunder method to enable native sorting and heapq priority queue compatibility"],
     "Build classes, manage instance state, and implement dunder protocols (__repr__, __eq__, __hash__, and __lt__ for comparators)."),
    (23, "python-core", "Inheritance & Method Resolution Order (C3)", "Inheritance Models", 30, "FOUNDATIONAL", [22], "tier2", "tracing",
     ["Single & Multiple Inheritance", "C3 Linearization & super()"],
     ["Trace multiple inheritance lookup order using C3 linearization MRO", "Coordinate cooperative super() initialization across class hierarchies"],
     "Master single and multiple inheritance, super(), and CPython's C3 Linearization Method Resolution Order (MRO)."),
    (24, "python-core", "Exception Handling & Custom Hierarchies", "Error Architecture", 25, "FOUNDATIONAL", [22], "tier1", "debugging",
     ["try/except/else/finally", "Custom Exception Hierarchies"],
     ["Refactor broad exception handlers into precise catch blocks with cleanup guarantees", "Define domain-specific custom exception classes inheriting from Exception"],
     "Write robust error-handling code with try/except/else/finally and build custom domain exception classes."),
    (25, "python-core", "Python DSA Algorithmic Toolkit & Milestone", "Core Milestone", 45, "FOUNDATIONAL", [11, 14, 15, 18, 22], "tier3", "milestone",
     ["list.sort() vs sorted() & Multi-Key", "heapq & Tie-Breaker Crash Prevention", "sys.setrecursionlimit & Float Infinity"],
     ["Sort complex structures with multi-key tuple lambdas and utilize heapq min-heaps safely", "Configure recursion limits (sys.setrecursionlimit) and sentinel infinities for algorithmic problem solving"],
     "Synthesize Python core data structures into a complete algorithmic toolkit bridging into Data Structures & Algorithms."),

    # Sec 3 (26-35)
    (26, "computational-thinking", "Asymptotic Analysis & Big-O Notation", "Complexity Foundations", 30, "DEVELOPING", [25], "tier1", "tracing",
     ["Big-O Asymptotic Upper Bound", "Growth Orders (O(1) to O(2^N))"],
     ["Classify mathematical functions by asymptotic growth rate as N approaches infinity", "Differentiate best-case, average-case, and worst-case performance metrics"],
     "Understand Big-O notation, asymptotic upper bounds, growth rate hierarchies, and worst-case vs average-case behavior."),
    (27, "computational-thinking", "Identifying Common Time Complexities", "Code Complexity Analysis", 30, "DEVELOPING", [26], "tier1", "tracing",
     ["Nested Loops & Stride Halving", "Drop Constants & Non-Dominant Terms"],
     ["Analyze code snippets to extract time complexity formulas by inspecting loop bounds", "Identify logarithmic complexity in divide-by-two search and stride halving patterns"],
     "Analyze code snippets to determine O(1), O(log N), O(N), O(N log N), O(N^2), and O(2^N) time complexities."),
    (28, "computational-thinking", "Space Complexity & Auxiliary Memory", "Space Analysis", 25, "DEVELOPING", [27], "tier1", "tracing",
     ["Auxiliary Space vs Input Space", "Call Stack Frame Allocation"],
     ["Calculate auxiliary heap memory consumption independently of input storage", "Account for maximum call stack depth when computing recursive space complexity"],
     "Differentiate total space from auxiliary space, measure memory allocations, and analyze recursion stack overhead."),
    (29, "computational-thinking", "Brute Force to Optimized Reductions", "Optimization Strategies", 35, "DEVELOPING", [27, 28], "tier2", "debugging",
     ["Bottleneck Identification", "Trading Space for Time"],
     ["Identify algorithmic bottlenecks that degrade procedures into quadratic runtimes", "Refactor O(N^2) brute-force searches into linear O(N) pipelines using hash lookups"],
     "Learn systematic techniques to recognize quadratic bottlenecks and optimize them using precomputation or hash tables."),
    (30, "computational-thinking", "Linear Recursion Fundamentals & Call Stack", "Recursion Foundations", 35, "DEVELOPING", [6, 28], "tier2", "tracing",
     ["Base Case & Recursive Step", "Call Stack Unwinding & Frame Allocation"],
     ["Formulate inductive base cases and recursive steps that guarantee termination", "Trace recursive call stack frame allocation, state isolation, and return unwinding"],
     "Master base cases, recursive steps, stack frame allocation, stack unwinding, and recursion depth limits."),
    (31, "computational-thinking", "Branching Recursion & Tree Diagramming", "Branching Recursion", 40, "DEVELOPING", [30], "tier2", "tracing",
     ["Multiple Recursive Calls & Branching", "Recursion Tree Level Work"],
     ["Model multi-branch recursive algorithms using visual recursion tree diagrams", "Compute total work by summing level work across tree depths to explain O(2^N) explosion"],
     "Analyze branching recursion, tree representations of recursive calls, redundant work in Fibonacci, and work per level."),
    (32, "computational-thinking", "Tail Recursion & State Accumulators", "Tail Recursion", 30, "DEVELOPING", [30], "tier2", "algorithm",
     ["Tail Call Position", "Accumulator Passing Style"],
     ["Convert head recursion into tail-call form using accumulator parameters", "Transform linear recursive procedures into iterative loops to prevent stack overflow"],
     "Understand tail calls, accumulator parameters, transforming recursion to iteration, and Python recursion limitations."),
    (33, "computational-thinking", "Divide & Conquer Master Theorem", "Recurrence Analysis", 30, "DEVELOPING", [31], "tier1", "tracing",
     ["Divide, Conquer, Combine Paradigm", "Master Theorem Cases"],
     ["Formulate recurrence relations T(N) = aT(N/b) + f(N) for divide-and-conquer algorithms", "Apply the three cases of the Master Theorem to deduce exact asymptotic complexity"],
     "Formulate recurrence relations and apply the Master Theorem to divide-and-conquer recurrences T(n) = aT(n/b) + f(n)."),
    (34, "computational-thinking", "Invariant Design & Loop Verification", "Algorithmic Invariants", 30, "DEVELOPING", [27], "tier1", "completion",
     ["Loop Invariant Specification", "Initialization, Maintenance & Termination"],
     ["Specify inductive loop invariants that prove algorithmic correctness", "Verify initialization, maintenance, and termination conditions for array loops"],
     "Formalize algorithm correctness using loop invariants: initialization, maintenance, and termination proof techniques."),
    (35, "computational-thinking", "Section 3 Milestone & Complexity Audit", "Complexity Milestone", 45, "DEVELOPING", [26, 27, 28, 30, 31, 33, 34], "tier3", "milestone",
     ["Asymptotic Profiling", "Space-Time Tradeoff Design", "Formal Invariant Proof"],
     ["Conduct a comprehensive asymptotic audit optimizing three distinct algorithmic routines", "Formulate mathematical correctness proofs and recurrence trees under interview constraints"],
     "Perform an end-to-end complexity audit and algorithmic proof evaluation across recursion, iterative state, and recurrences."),

    # Sec 4 (36-50)
    (36, "arrays-and-strings", "Static vs Dynamic Arrays & Cache Locality", "Array Memory", 30, "DEVELOPING", [11, 27], "tier1", "tracing",
     ["Contiguous Physical Memory", "CPU Cache Lines & Stride Locality"],
     ["Contrast fixed memory allocations with dynamic pointer arrays", "Predict CPU cache hits and misses across row-major vs column-major matrix sweeps"],
     "Understand physical contiguous arrays, memory layouts, CPU cache line caching, and access patterns."),
    (37, "arrays-and-strings", "1D Prefix Sums & O(1) Range Queries", "Prefix Sums", 35, "DEVELOPING", [36], "tier2", "algorithm",
     ["Prefix Sum Array Construction", "O(1) Range Sum Formula"],
     ["Construct a 1-indexed prefix sum array in O(N) preprocessing time", "Answer arbitrary range sum queries (L to R) in strict O(1) time"],
     "Construct 1D prefix sum arrays to answer range sum queries in O(1) time after O(N) precomputation."),
    (38, "arrays-and-strings", "Difference Arrays & Range Updates", "Difference Arrays", 35, "DEVELOPING", [37], "tier2", "algorithm",
     ["Difference Array Invariant", "O(1) Range Updates with O(N) Reconstruction"],
     ["Execute range increment updates in O(1) time by mutating difference boundary indices", "Reconstruct final array values in a single O(N) prefix summation pass"],
     "Master difference arrays for O(1) range updates followed by a single O(N) prefix sum reconstruction."),
    (39, "arrays-and-strings", "Two Pointers: Opposing Direction", "Two Pointers", 35, "DEVELOPING", [34, 36], "tier2", "problem",
     ["Converging Boundary Pointers", "Monotonic Search Space Elimination"],
     ["Eliminate suboptimal search space candidates monotonically using inward-converging pointers", "Solve two-sum on sorted arrays and Container With Most Water in O(N) time and O(1) space"],
     "Use two pointers moving inward from boundaries to solve two-sum on sorted arrays and maximize area."),
    (40, "arrays-and-strings", "Two Pointers: Fast & Slow In-Place Writers", "In-Place Pointers", 30, "DEVELOPING", [39], "tier2", "completion",
     ["Read/Write Pointer Invariant", "In-Place Array Compaction"],
     ["Maintain read and write pointer invariants for in-place array compaction", "Remove duplicates and shift elements in-place without allocating auxiliary lists"],
     "Implement fast and slow pointers for in-place array mutation, deduplication, and zero-shifting in O(1) space."),
    (41, "arrays-and-strings", "Sliding Window: Fixed Size", "Fixed Window", 35, "DEVELOPING", [37, 40], "tier2", "problem",
     ["Rolling Window State", "O(1) Element Slide Transition"],
     ["Maintain rolling window state across fixed length k by adding incoming and subtracting outgoing elements", "Compute maximum subarray sums and rolling averages in O(N) time"],
     "Apply fixed-size sliding windows to compute rolling sums, max averages, and contiguous subarray statistics in O(N) time."),
    (42, "arrays-and-strings", "Sliding Window: Dynamic Size", "Dynamic Window", 40, "DEVELOPING", [41], "tier2", "problem",
     ["Expand-Right & Contract-Left", "Monotonic Condition Predicates"],
     ["Expand right pointers to find valid subsegments and contract left pointers to restore invariants", "Solve the Longest Substring Without Repeating Characters in O(N) time"],
     "Master dynamic sliding windows that expand and contract based on validity predicates, solving substring problems."),
    (43, "arrays-and-strings", "Kadane's Algorithm & Maximum Subarray", "Subarray Optimization", 35, "DEVELOPING", [37], "tier2", "algorithm",
     ["Kadane's Local vs Global Maxima", "Subarray Reset Condition"],
     ["Formulate the local choice invariant: extend existing subarray or start fresh from current element", "Implement Kadane's algorithm tracking maximum sum and subarray boundary indices in O(N) time and O(1) space"],
     "Implement Kadane's algorithm to find maximum contiguous subarray sums in O(N) time and O(1) space, with boundary tracking."),
    (44, "arrays-and-strings", "In-Place Array Rotation & Reversal", "Array Manipulations", 30, "DEVELOPING", [40], "tier2", "debugging",
     ["Triple-Reversal Algorithm", "Block Swap Invariants"],
     ["Rotate arrays by k positions in O(N) time and O(1) auxiliary space using triple reversals", "Debug off-by-one pointer swaps on odd and even length segments"],
     "Rotate arrays in O(1) auxiliary space using the three-reversal trick, cyclic replacements, and block swapping."),
    (45, "arrays-and-strings", "String Parsing & State Machine Tokenization", "String State Machines", 40, "DEVELOPING", [3, 44], "tier3", "algorithm",
     ["Deterministic Finite Automata (DFA)", "Edge Case Parsing Guardrails"],
     ["Design a deterministic finite automaton state machine to parse strings into typed tokens", "Implement robust string-to-integer conversion (atoi) handling leading whitespace, signs, and clamping"],
     "Build state machines to parse complex strings, validate numeric formats, and implement string-to-integer (atoi)."),
    (46, "arrays-and-strings", "Palindrome Verification & Center Expansion", "Palindromes", 35, "DEVELOPING", [39, 45], "tier2", "problem",
     ["Center Expansion Paradigm", "Odd vs Even Length Palindromes"],
     ["Expand around 2N - 1 potential centers to identify palindromic substrings in O(N^2) time and O(1) space", "Verify alphanumeric palindrome sentences using two pointers skipping non-alphanumeric characters"],
     "Verify palindromes using two pointers and find longest palindromic substrings by expanding around 2N-1 centers."),
    (47, "arrays-and-strings", "2D Matrix Traversals & Spiral Order", "Matrix Algorithms", 35, "DEVELOPING", [36], "tier2", "problem",
     ["Matrix Boundary Invariants", "Directional Offset Stepping"],
     ["Traverse an M x N matrix in spiral order while updating top, bottom, left, and right boundary limits", "Rotate matrices 90 degrees in-place by transposing and reversing rows"],
     "Navigate 2D grids, extract diagonals, rotate matrices in-place, and traverse boundary spirals without allocations."),
    (48, "arrays-and-strings", "2D Prefix Sums & Matrix Accumulation", "2D Prefix Sums", 40, "DEVELOPING", [37, 47], "tier3", "algorithm",
     ["Inclusion-Exclusion Principle", "O(1) Submatrix Sum Queries"],
     ["Construct a 2D prefix sum table using the 2D inclusion-exclusion principle", "Evaluate arbitrary submatrix sum queries in strict O(1) time"],
     "Construct 2D prefix sum tables using the inclusion-exclusion principle to query rectangular submatrix sums in O(1) time."),
    (49, "arrays-and-strings", "Intervals: Sorting & Merging Overlaps", "Interval Scheduling", 35, "DEVELOPING", [25, 40], "tier2", "problem",
     ["Interval Overlap Invariant", "Greedy Interval Merging"],
     ["Sort intervals by start times and merge overlapping segments in O(N log N) time", "Determine non-overlapping intervals and schedule rooms using boundary scan lines"],
     "Sort intervals, merge overlapping ranges, insert new intervals, and determine interval intersections in O(N log N) time."),
    (50, "arrays-and-strings", "Section 4 Capstone: Linear Array Patterns", "Array Capstone", 45, "DEVELOPING", [37, 39, 41, 43, 49], "tier3", "milestone",
     ["Pattern Hybridization", "Composite Data Pipelines", "Production Bounds"],
     ["Synthesize prefix sums, two pointers, and interval merges to architect a calendar engine", "Optimize compound array queries meeting strict O(N) time constraints"],
     "Synthesize two-pointers, sliding windows, prefix sums, and interval merging into a composite challenge."),

    # Sec 5 (51-65)
    (51, "searching-and-sorting", "Linear Search vs Binary Search Halving", "Search Foundations", 30, "DEVELOPING", [27, 36], "tier1", "tracing",
     ["Linear Scan vs Logarithmic Halving", "Search Space Invariant"],
     ["Trace binary search interval halving and logarithmic depth bounds", "Prove necessity of sorted order before applying binary search"],
     "Contrast linear search with binary search, proving O(log N) runtime through search-space halving."),
    (52, "searching-and-sorting", "Classical Binary Search & Boundary Indices", "Binary Search Boundaries", 35, "DEVELOPING", [51], "tier2", "completion",
     ["Midpoint Calculation (L + (R-L)//2)", "Bisect Left & Right Boundaries"],
     ["Prevent integer overflow bugs in midpoint computation", "Implement exact lower-bound and upper-bound binary searches (bisect_left / bisect_right)"],
     "Master boundary conditions, lower and upper bounds, bisect semantics, and avoiding infinite loops in binary search."),
    (53, "searching-and-sorting", "Binary Search on Monotonic Answer Space", "Answer Space Search", 40, "DEVELOPING", [52], "tier2", "problem",
     ["Monotonic Feasibility Predicate", "Answer Space Search Invariant"],
     ["Map optimization problems to monotonic boolean check functions", "Solve Capacity to Ship Packages and Koko Eating Bananas in O(N log(Range)) time"],
     "Apply binary search to monotonic answer spaces to find optimal parameters meeting problem constraints."),
    (54, "searching-and-sorting", "Rotated Sorted Arrays & Peak Finding", "Rotated Search", 35, "DEVELOPING", [52], "tier2", "debugging",
     ["Sorted Half Identification", "Inflection Point Invariants"],
     ["Determine which half of a rotated sorted array is monotonically ordered", "Locate target elements and inflection minimums in O(log N) time"],
     "Find elements in rotated sorted arrays and locate local peaks using modified binary search predicates."),
    (55, "searching-and-sorting", "Quadratic Sorts: Bubble, Selection, Insertion", "Quadratic Sorts", 30, "DEVELOPING", [34, 36], "tier1", "debugging",
     ["Insertion Sort Invariant", "Stability in Sorting Algorithms"],
     ["Explain why insertion sort achieves linear O(N) performance on nearly-sorted data", "Debug sorting stability violations where equal keys are unintentionally swapped"],
     "Analyze Bubble, Selection, and Insertion Sort, proving O(N^2) bounds and stability trade-offs."),
    (56, "searching-and-sorting", "Merge Sort: Divide, Conquer, Combine", "Merge Sort", 45, "DEVELOPING", [31, 33, 55], "tier3", "algorithm",
     ["Divide & Conquer Merge Step", "Stable O(N log N) Guarantee"],
     ["Implement recursive Merge Sort with linear merge combination passes", "Analyze O(N log N) time and O(N) auxiliary space requirements"],
     "Implement Merge Sort recursively, trace recursion trees, and prove the O(N log N) stable sorting guarantee."),
    (57, "searching-and-sorting", "Quick Sort & Hoare Partitioning", "Quick Sort", 45, "DEVELOPING", [31, 56], "tier3", "algorithm",
     ["Hoare vs Lomuto Partitioning", "Pivot Selection & O(N^2) Degeneracy"],
     ["Implement in-place Hoare partition scheme with median-of-three pivot selection", "Explain worst-case O(N^2) degradation on sorted inputs and randomization fixes"],
     "Implement Quick Sort, master Lomuto and Hoare partitioning, analyze expected O(N log N) time, and avoid worst-case pivots."),
    (58, "searching-and-sorting", "Quickselect: Expected O(N) Kth Order", "Order Statistics", 35, "DEVELOPING", [57], "tier2", "completion",
     ["Single-Sided Partition Discarding", "Expected O(N) Recurrence"],
     ["Discard non-promising partitions to locate the Kth largest element in expected O(N) time", "Prove the geometric series convergence T(N) = N + N/2 + N/4 = 2N"],
     "Use Quickselect to find the Kth smallest or largest element in expected O(N) time without full sorting."),
    (59, "searching-and-sorting", "Counting Sort & Non-Comparison Bounds", "Counting Sort", 35, "DEVELOPING", [36, 56], "tier2", "algorithm",
     ["Non-Comparison Sorting Invariant", "Cumulative Frequency Offsets"],
     ["Bypass the Omega(N log N) comparison sort lower bound using frequency arrays", "Implement stable Counting Sort in O(N + K) time and O(K) space"],
     "Break the Omega(N log N) comparison barrier with stable Counting Sort over bounded integer ranges."),
    (60, "searching-and-sorting", "Radix Sort & Bucket Sort", "Distribution Sorts", 40, "DEVELOPING", [59], "tier3", "algorithm",
     ["LSD vs MSD Radix Passes", "Bucket Sort Distribution"],
     ["Implement Least Significant Digit (LSD) Radix Sort across fixed integer representations", "Distribute uniform floating-point keys into buckets in O(N) average time"],
     "Implement Radix Sort and Bucket Sort for linear-time sorting of fixed-width integers and uniform numbers."),
    (61, "searching-and-sorting", "Python's Timsort Architecture", "Timsort Architecture", 35, "DEVELOPING", [56, 60], "tier2", "tracing",
     ["Natural Runs & Galloping Mode", "Minrun Computation & Stack Balance"],
     ["Trace natural ascending and descending run identification in Python's list.sort()", "Explain binary insertion sort integration on sub-arrays under minrun thresholds"],
     "Examine Python's built-in Timsort algorithm, minruns, run merging invariants, and galloping mode."),
    (62, "searching-and-sorting", "Custom Comparators & Multi-Key Sorting", "Custom Sorting", 30, "DEVELOPING", [22, 25, 61], "tier1", "completion",
     ["key Function Lambdas", "Multi-Attribute Tuple Keys"],
     ["Construct complex multi-key sorting pipelines using tuple keys and reverse flags", "Bridge legacy three-way comparators using functools.cmp_to_key"],
     "Master Python's key parameter in sorted(), multi-level tuple keys, and functools.cmp_to_key."),
    (63, "searching-and-sorting", "Inversion Counting with Merge Sort", "Inversion Counting", 35, "DEVELOPING", [56], "tier2", "problem",
     ["Inversion Pair Invariant", "Merge Step Accumulation"],
     ["Count array inversions in O(N log N) time by instrumenting the Merge Sort merge phase", "Deduce remaining inversions when an element from the right array is selected first"],
     "Count the number of inverted pairs in an array in O(N log N) time by augmenting the merge sort procedure."),
    (64, "searching-and-sorting", "Ternary Search on Unimodal Functions", "Ternary Search", 30, "DEVELOPING", [51], "tier1", "algorithm",
     ["Unimodal Function Extremum", "Trisection Convergence"],
     ["Locate the extremum of a unimodal continuous function via search-space trisection", "Prove the 2/3 range reduction factor per iteration"],
     "Apply ternary search to find extrema of unimodal functions by dividing intervals into three equal segments."),
    (65, "searching-and-sorting", "Section 5 Review & Search/Sort Mastery", "Search & Sort Milestone", 45, "DEVELOPING", [52, 53, 56, 57, 61, 62], "tier3", "milestone",
     ["Search/Sort Hybridization", "Asymptotic Trade-off Selection", "Adaptive Pipelines"],
     ["Design a high-performance hybrid sorting algorithm dynamically switching strategies at threshold K", "Solve composite placement interview problems under strict time and space budgets"],
     "Synthesize binary search paradigms, comparison and non-comparison sorting algorithms, and custom comparators."),

    # Sec 6 (66-75)
    (66, "hashing-and-hash-tables", "Hash Functions, Prime Moduli & Distribution", "Hash Functions", 30, "DEVELOPING", [15, 27], "tier1", "tracing",
     ["Uniform Distribution & Avalanche Effect", "Prime Modulo Bucketing"],
     ["Evaluate hash functions on key avalanche and uniformity metrics", "Apply prime modulus division to minimize bucket collisions"],
     "Understand hash function properties: uniformity, determinism, avalanche effect, and prime-number modulo bucketing."),
    (67, "hashing-and-hash-tables", "Collision Resolution: Chaining vs Probing", "Collision Resolution", 35, "DEVELOPING", [66], "tier2", "algorithm",
     ["Separate Chaining with Buckets", "Linear & Quadratic Probing"],
     ["Implement a hash map resolving collisions via separate chaining buckets", "Trace open addressing probing sequences and tombstone deletion markers"],
     "Implement collision resolution via separate chaining and open addressing (linear, quadratic, and double hashing)."),
    (68, "hashing-and-hash-tables", "Frequency Counting & Anagram Detection", "Frequency Hashing", 30, "DEVELOPING", [3, 17, 67], "tier1", "problem",
     ["Fixed Alphabet Frequency Arrays", "Valid Anagram Verification"],
     ["Count character frequencies in O(N) time and O(1) auxiliary space using ord() offsets", "Determine anagram equivalence without sorting inputs"],
     "Use frequency tables and hash maps to solve anagram detection and character count equality in O(N) time."),
    (69, "hashing-and-hash-tables", "Subarray Sums = K with Prefix Hash Maps", "Prefix Hash Maps", 40, "DEVELOPING", [37, 68], "tier2", "problem",
     ["Prefix Sum Frequency Invariant", "Two-Sum Reduction (pref - k)"],
     ["Store cumulative prefix sum frequencies in a hash table to find target subarrays", "Solve Subarray Sum Equals K in O(N) time and O(N) space"],
     "Combine prefix sums with hash maps to count contiguous subarrays summing to K in O(N) time."),
    (70, "hashing-and-hash-tables", "Grouping & Canonical Equivalence Keys", "Equivalence Hashing", 30, "DEVELOPING", [14, 68], "tier1", "problem",
     ["Canonical Representation Tuple", "Multi-Element Grouping"],
     ["Construct immutable tuple signature keys to partition elements into equivalence classes", "Group anagrams in O(N * K) time without expensive string sorts"],
     "Design canonical hash keys to group anagrams, coordinate patterns, and equivalence classes in O(N * K) time."),
    (71, "hashing-and-hash-tables", "Hash Sets for O(1) Consecutive Sequences", "Sequence Hashing", 35, "DEVELOPING", [17, 70], "tier2", "problem",
     ["Sequence Start Verification (num - 1)", "O(1) Set Membership Streak"],
     ["Identify sequence heads by checking absence of (num - 1) in a hash set", "Find the Longest Consecutive Sequence in an unsorted array in strict O(N) time"],
     "Find the longest consecutive integer sequence in unsorted arrays in O(N) time using O(1) hash set lookups."),
    (72, "hashing-and-hash-tables", "Rolling Hash & Rabin-Karp Substring Search", "Rolling Hash", 45, "DEVELOPING", [45, 66], "tier3", "algorithm",
     ["Polynomial Rolling Hash Formula", "Spurious Hit Spurious Verification"],
     ["Implement the polynomial rolling hash window slide formula in O(1) update time", "Execute the Rabin-Karp substring search algorithm with prime modulo hashing"],
     "Implement polynomial rolling hashes and the Rabin-Karp algorithm for average O(N + M) substring matching."),
    (73, "hashing-and-hash-tables", "LRU Cache Architecture via OrderedDict", "OrderedDict LRU", 35, "DEVELOPING", [18, 67], "tier2", "algorithm",
     ["Doubly Linked Hash Table Concept", "O(1) Move-to-End Eviction"],
     ["Implement an LRU Cache in O(1) time using Python's collections.OrderedDict", "Manage key eviction policies under fixed capacity limits"],
     "Build an O(1) Least Recently Used (LRU) Cache utilizing collections.OrderedDict as an introductory bridge."),
    (74, "hashing-and-hash-tables", "LFU Cache Design Principles", "LFU Cache", 45, "DEVELOPING", [73], "tier3", "milestone",
     ["Frequency Bucket Doubly Linked Lists", "Min-Frequency Pointer Invariant"],
     ["Design an LFU cache tracking access frequencies and secondary recency orders", "Maintain min_freq tracking in O(1) time across get and put operations"],
     "Architect an O(1) Least Frequently Used (LFU) cache using nested frequency buckets and reciprocal pointers."),
    (75, "hashing-and-hash-tables", "Section 6 Review & Hashing Mastery", "Hashing Milestone", 40, "DEVELOPING", [67, 69, 70, 71, 72, 73], "tier2", "milestone",
     ["Hash Table Architectural Trade-offs", "Collision Resistance", "Cache Policy Integration"],
     ["Evaluate hash table designs under adversarial collision attack scenarios", "Synthesize hash tables and sliding windows into an optimal streaming lookup pipeline"],
     "Synthesize hash maps, hash sets, rolling hashes, and cache architectures into a complete caching engine."),

    # Sec 7 (76-85)
    (76, "linked-lists", "Singly Linked List: Structure & Traversal", "Linked List Basics", 30, "INTERMEDIATE", [22, 36], "tier1", "guided",
     ["ListNode Pointer Reference", "Sequential Pointer Traversal"],
     ["Construct a custom ListNode class and traverse nodes until curr is None", "Contrast linked list dynamic pointer chains with contiguous array memory"],
     "Define ListNode nodes, manage head references, traverse lists, and analyze non-contiguous heap allocations."),
    (77, "linked-lists", "Insertion, Deletion & Dummy Sentinels", "Sentinel Nodes", 35, "INTERMEDIATE", [76], "tier1", "completion",
     ["Dummy Sentinel Head Node", "Predecessor Pointer Rewiring"],
     ["Eliminate head edge-case conditionals using a dummy sentinel node", "Insert and delete interior list nodes in O(1) pointer operations given predecessor"],
     "Use dummy sentinel nodes to eliminate special cases when inserting or deleting nodes at list boundaries."),
    (78, "linked-lists", "In-Place Linked List Pointer Reversal", "List Reversal", 35, "INTERMEDIATE", [77], "tier2", "debugging",
     ["Three-Pointer Iterative Reversal", "next_node Forward Caching"],
     ["Cache forward references in next_node before mutating curr.next to prev", "Reverse a singly linked list in-place in O(N) time and O(1) space"],
     "Reverse singly linked lists iteratively in O(N) time and O(1) space using three pointers (prev, curr, next_node)."),
    (79, "linked-lists", "Fast & Slow Pointers (Tortoise & Hare)", "Runner Technique", 35, "INTERMEDIATE", [78], "tier2", "completion",
     ["2x Speed Differential", "Midpoint & Kth-from-End Extraction"],
     ["Locate the exact midpoint of a linked list in a single pass using runner pointers", "Extract the Kth node from the end using a fixed-gap pointer pair"],
     "Use the fast and slow pointer technique to find list midpoints and Kth-from-end nodes in a single traversal."),
    (80, "linked-lists", "Floyd's Cycle Detection & Entry Proof", "Cycle Detection", 40, "INTERMEDIATE", [79], "tier3", "algorithm",
     ["Floyd's Tortoise & Hare Cycle", "Mathematical Entry Point Derivation"],
     ["Detect whether a linked list contains a cycle without auxiliary hash sets", "Prove mathematically that moving one pointer from head matches the cycle entry node"],
     "Implement Floyd's Cycle Detection algorithm, prove 2k - k = k cycle convergence, and locate cycle start nodes."),
    (81, "linked-lists", "Merge Two Sorted Lists & K-Way Splicing", "List Merging", 35, "INTERMEDIATE", [77, 78], "tier2", "problem",
     ["Sentinel Splice Invariant", "Iterative In-Place Splice"],
     ["Merge two sorted singly linked lists in-place in O(N + M) time without new allocations", "Splice node pointers monotonically preserving sorted sequence"],
     "Merge two sorted linked lists in-place in O(N1 + N2) time and introduce K-way list splicing."),
    (82, "linked-lists", "Doubly Linked Lists & Bi-Directional Nodes", "Doubly Linked Lists", 30, "INTERMEDIATE", [77], "tier1", "algorithm",
     ["prev & next Bi-Directional Pointers", "O(1) Self-Detachment"],
     ["Implement a Doubly Linked List node with prev and next references", "Detach arbitrary interior nodes in strict O(1) time without finding predecessor"],
     "Implement Doubly Linked Lists, manage prev/next pointers, and achieve O(1) arbitrary node detachment."),
    (83, "linked-lists", "Scratch-Built LRU Cache (DLL + Hash Map)", "Scratch LRU Cache", 45, "INTERMEDIATE", [73, 82], "tier3", "milestone",
     ["Hash Map to DLL Node Pointers", "O(1) get() and put() Operations"],
     ["Architect a complete LRU Cache from scratch pairing a hash map with a doubly linked list", "Maintain head/tail dummy sentinels to guarantee O(1) eviction and promotion"],
     "Build a production-grade O(1) LRU Cache from scratch combining a Hash Map with a Doubly Linked List with sentinels."),
    (84, "linked-lists", "Reverse Nodes in K-Group", "K-Group Reversal", 45, "INTERMEDIATE", [78, 81], "tier3", "problem",
     ["K-Node Segment Isolation", "Boundary Pointer Re-Wiring"],
     ["Count and reverse contiguous subsegments of k nodes in-place", "Reconnect reversed segment endpoints cleanly to preceding and following sublists"],
     "Reverse linked lists in groups of K nodes, handling subsegment reversals and boundary reconnects in O(N) time."),
    (85, "linked-lists", "Section 7 Review & Pointer Discipline", "Linked List Milestone", 40, "INTERMEDIATE", [78, 80, 81, 83, 84], "tier2", "milestone",
     ["Pointer Leak Prevention", "In-Place List Merge Sort", "Sentinel Standardization"],
     ["Sort linked lists in O(N log N) time and O(log N) stack space using linked list merge sort", "Audit pointer manipulation logic against cyclic reference leaks and lost heads"],
     "Synthesize pointer manipulation disciplines, sentinel architectures, and recursive linked-list sorting."),

    # Sec 8 (86-95)
    (86, "stacks-and-queues", "Stack LIFO Mechanics & Array Backing", "Stack Foundations", 30, "INTERMEDIATE", [11, 28], "tier1", "guided",
     ["LIFO Ordering & Operations", "Stack Overflow & Underflow Guards"],
     ["Implement an array-backed stack with O(1) push, pop, and peek operations", "Enforce defensive bounds checking against stack underflow"],
     "Understand Last-In-First-Out (LIFO) stack mechanics, amortized O(1) list backing, and underflow guards."),
    (87, "stacks-and-queues", "Parentheses Matching & Balanced Syntax", "Balanced Syntax", 30, "INTERMEDIATE", [86], "tier1", "problem",
     ["Closing-to-Opening Hash Map", "Stack Emptiness Termination Invariant"],
     ["Validate nested bracket syntax by matching closing brackets against the stack top", "Determine syntax correctness in O(N) time and O(N) space"],
     "Solve balanced parentheses matching with multiple bracket types in O(N) time using a LIFO stack."),
    (88, "stacks-and-queues", "Min-Stack Design with O(1) Retrieval", "Min-Stack", 35, "INTERMEDIATE", [86], "tier1", "algorithm",
     ["Auxiliary Min-Tracker Stack", "Value-Min State Tuples"],
     ["Architect a stack supporting getMin() in strict O(1) time alongside push() and pop()", "Maintain running minimum invariants across push and pop mutations"],
     "Design a stack supporting push, pop, top, and retrieving the minimum element in O(1) auxiliary time."),
    (89, "stacks-and-queues", "Queue FIFO Mechanics & Circular Ring Buffers", "Queue Foundations", 35, "INTERMEDIATE", [11, 86], "tier1", "algorithm",
     ["FIFO Ordering & Head/Tail Indices", "Circular Ring Buffer Modulo Math"],
     ["Implement a fixed-capacity circular queue using head, tail, and modulo index arithmetic", "Explain why list.pop(0) causes O(N) degradation and how ring buffers achieve O(1)"],
     "Implement First-In-First-Out (FIFO) queue semantics, circular array buffers, and avoid list pop(0) penalties."),
    (90, "stacks-and-queues", "Implement Queue Using Two Stacks", "Two-Stack Queue", 30, "INTERMEDIATE", [86, 89], "tier1", "algorithm",
     ["Input Stack & Output Stack", "Amortized O(1) Transfer Invariant"],
     ["Simulate FIFO queue behavior using two LIFO stacks", "Prove amortized O(1) time per element using potential function accounting"],
     "Implement a FIFO queue using two LIFO stacks, proving amortized O(1) time per operation via lazy transfers."),
    (91, "stacks-and-queues", "Monotonic Stack: Next Greater Element", "Monotonic Stack", 40, "INTERMEDIATE", [86], "tier2", "problem",
     ["Monotonically Decreasing Stack", "Immediate Pop Resolution"],
     ["Maintain a monotonically decreasing stack of array indices to find next greater elements", "Process array elements in O(N) total time by amortizing pushes and pops"],
     "Master the monotonic stack pattern to solve Next Greater Element and stock span problems in linear O(N) time."),
    (92, "stacks-and-queues", "Monotonic Stack: Largest Histogram Rectangle", "Histogram Monotonic Stack", 45, "INTERMEDIATE", [91], "tier3", "problem",
     ["Left & Right Smaller Bounds", "Width Calculation from Popped Index"],
     ["Calculate maximum rectangular area under a histogram in O(N) time using a monotonic stack", "Extend histogram algorithms to solve Maximal Rectangle in 2D binary matrices"],
     "Apply monotonic stacks to compute the largest rectangular area in histograms and maximal binary rectangles in O(N) time."),
    (93, "stacks-and-queues", "Monotonic Queue & Sliding Window Maximum", "Monotonic Queue", 40, "INTERMEDIATE", [18, 91], "tier2", "problem",
     ["Monotonically Decreasing Deque", "Out-of-Window Index Eviction"],
     ["Maintain a double-ended queue storing candidate maximums in strictly descending order", "Solve the Sliding Window Maximum problem in strict O(N) time and O(K) space"],
     "Implement monotonic double-ended queues (deques) to solve the Sliding Window Maximum problem in O(N) time."),
    (94, "stacks-and-queues", "Expression Parsing & Shunting-Yard Algorithm", "Expression Parsing", 45, "INTERMEDIATE", [86, 87], "tier3", "algorithm",
     ["Operator Precedence & Associativity", "Dijkstra's Shunting-Yard (Infix to Postfix)"],
     ["Convert infix mathematical expressions into postfix Reverse Polish Notation (RPN)", "Evaluate composite arithmetic expressions containing parentheses, +, -, *, / in O(N) time"],
     "Implement Dijkstra's Shunting-Yard algorithm to parse infix expressions into postfix RPN and evaluate them."),
    (95, "stacks-and-queues", "Section 8 Review & Linear State Machines", "Stacks & Queues Milestone", 40, "INTERMEDIATE", [87, 88, 91, 92, 93, 94], "tier2", "milestone",
     ["Linear Data Structure Selection", "State Machine Buffer Coordination", "Amortized Bounds"],
     ["Architect a calculator engine evaluating nested expressions with unary operators", "Select optimal stack and queue structures matching problem invariants"],
     "Synthesize stacks, queues, deques, and monotonic patterns into a complete expression and state evaluation engine."),

    # Sec 9 (96-110)
    (96, "trees-and-bst", "Tree Terminology & Hierarchical Anatomy", "Tree Foundations", 30, "INTERMEDIATE", [76], "tier1", "guided",
     ["Hierarchical Node Anatomy", "Height, Depth & Edge Counts"],
     ["Define a binary tree TreeNode class and recursive child pointer structures", "Calculate tree height, node depths, and verify leaf node conditions"],
     "Understand tree terminology: root, leaves, depth, height, ancestor/descendant relationships, and TreeNode classes."),
    (97, "trees-and-bst", "Recursive Traversals: Pre, In, Post-Order", "Recursive Traversals", 35, "INTERMEDIATE", [30, 96], "tier2", "tracing",
     ["NLR, LNR, LRN Visiting Orders", "Call Stack Tree Traversal"],
     ["Trace Pre-order, In-order, and Post-order recursive visits across binary trees", "Predict visiting sequence output for tree construction and destruction"],
     "Implement recursive pre-order (NLR), in-order (LNR), and post-order (LRN) binary tree traversals in O(N) time."),
    (98, "trees-and-bst", "Iterative Tree Traversals via Explicit Stack", "Iterative Traversals", 40, "INTERMEDIATE", [86, 97], "tier2", "algorithm",
     ["Explicit Stack Simulation", "Left-Spine Descent Invariant"],
     ["Implement iterative in-order and pre-order tree traversals using an explicit stack", "Eliminate recursion overhead and prevent stack overflow on deep unbalanced trees"],
     "Implement pre-order, in-order, and post-order tree traversals iteratively using an explicit stack in O(N) time."),
    (99, "trees-and-bst", "BFS & Level-Order Queue Traversal", "Level-Order BFS", 35, "INTERMEDIATE", [89, 97], "tier2", "algorithm",
     ["FIFO Queue Level Batching", "Zigzag & Level Width Tracking"],
     ["Traverse binary trees level-by-level using a FIFO queue recording row arrays", "Compute level averages, tree widths, and zigzag level-order paths in O(N) time"],
     "Implement breadth-first search (BFS) level-order traversal on trees using queues, handling level batching."),
    (100, "trees-and-bst", "Tree Properties: Height, Diameter & Symmetry", "Tree Properties", 35, "INTERMEDIATE", [97], "tier2", "problem",
     ["Post-Order State Aggregation", "Global Diameter Calculation (Left + Right)"],
     ["Calculate maximum tree diameter by computing left and right branch heights bottom-up", "Verify binary tree mirror symmetry using recursive dual-node checks"],
     "Compute tree height, diameter, balance factors, and test tree symmetry using bottom-up post-order DFS in O(N) time."),
    (101, "trees-and-bst", "Binary Search Tree (BST) Invariant & Search", "BST Invariant", 35, "INTERMEDIATE", [52, 97], "tier2", "completion",
     ["Left < Root < Right Invariant", "Recursive Boundary Validation (low, high)"],
     ["Verify binary search tree validity by passing recursive open interval bounds (low, high)", "Search for target keys in O(H) time where H is tree height"],
     "Understand the BST property (Left < Root < Right), validate BST invariants, and perform O(H) key lookups."),
    (102, "trees-and-bst", "BST Insertion, Deletion & Successor Rewiring", "BST Mutations", 45, "INTERMEDIATE", [101], "tier3", "debugging",
     ["In-Order Successor Substitution", "Two-Child Deletion Rewiring"],
     ["Insert new values into BST leaf positions preserving the BST invariant", "Delete interior nodes with two children by substituting the in-order successor"],
     "Implement BST insertion and deletion, handling 0, 1, and 2-child cases and in-order successor replacements."),
    (103, "trees-and-bst", "Lowest Common Ancestor (LCA) in BST and Tree", "Lowest Common Ancestor", 35, "INTERMEDIATE", [101], "tier2", "problem",
     ["BST Value-Guided Bifurcation", "General Tree Dual-Branch DFS"],
     ["Find the LCA of two nodes in a BST in O(H) time using numerical value bifurcation", "Locate LCA in general binary trees using post-order node presence bubbling"],
     "Find the Lowest Common Ancestor (LCA) in BSTs in O(H) time and general binary trees in O(N) time via DFS."),
    (104, "trees-and-bst", "Tree Serialization & Deserialization", "Tree Serialization", 40, "INTERMEDIATE", [97, 99], "tier3", "algorithm",
     ["Pre-order String Representation", "None Marker Stream Reconstruction"],
     ["Encode a binary tree into a delimited string representation using pre-order traversal with null markers", "Reconstruct the identical tree structure from string tokens in O(N) time"],
     "Serialize binary trees into flat string representations and reconstruct them using pre-order and BFS iterators."),
    (105, "trees-and-bst", "Morris In-Order Traversal & Threaded Pointers", "Morris Traversal", 45, "INTERMEDIATE", [102], "tier3", "algorithm",
     ["In-Order Predecessor Rightmost Pointer", "O(1) Auxiliary Space Invariant"],
     ["Establish temporary threads from in-order predecessors to current nodes", "Traverse binary search trees in strictly O(1) auxiliary space without stack or recursion"],
     "Traverse binary trees in-order in O(1) auxiliary space using Morris Traversal and threaded binary tree pointers."),
    (106, "trees-and-bst", "Balanced BSTs: AVL Tree Rotations (LL, RR)", "AVL Rotations", 45, "INTERMEDIATE", [102], "tier3", "tracing",
     ["Height Balance Factor (-1, 0, +1)", "Single & Double Rotations (LL, RR, LR, RL)"],
     ["Calculate AVL node balance factors from left and right subtree heights", "Trace single and double tree rotations that restore O(log N) height balance"],
     "Understand AVL balance factors, height-balance invariants, and implement left and right tree rotations."),
    (107, "trees-and-bst", "Red-Black Tree Principles & Invariants", "Red-Black Trees", 35, "INTERMEDIATE", [106], "tier2", "tracing",
     ["Red/Black Color Invariants", "Black-Height Invariant & Recolor Rules"],
     ["Trace the 5 Red-Black tree properties guaranteeing maximum height <= 2 log(N+1)", "Differentiate recoloring steps from rotation steps during node insertion"],
     "Analyze Red-Black tree color invariants, black-height guarantees, and compare performance trade-offs against AVL trees."),
    (108, "trees-and-bst", "Tries (Prefix Trees): Structure & Lookup", "Trie Architecture", 35, "INTERMEDIATE", [15, 96], "tier2", "algorithm",
     ["26-Child Alphabet TrieNode", "is_end Word Termination Flag"],
     ["Implement a prefix Trie with insert, search, and startsWith methods in O(L) time", "Contrast Trie string prefix search with hash map string lookups"],
     "Build a Trie (Prefix Tree) data structure supporting O(L) word insertion, full-word search, and prefix matching."),
    (109, "trees-and-bst", "Trie Applications: Autocomplete & Wildcards", "Trie Applications", 40, "INTERMEDIATE", [108], "tier3", "problem",
     ["DFS Prefix Subtree Collection", "Wildcard '.' Branching Traversal"],
     ["Implement an autocomplete search engine returning all words sharing a common prefix", "Traverse all child branches upon encountering wildcard '.' characters"],
     "Apply Tries to autocomplete dictionary queries and wildcard pattern searches using recursive backtracking."),
    (110, "trees-and-bst", "Section 9 Review & Tree Recursion Mastery", "Trees Milestone", 45, "INTERMEDIATE", [100, 102, 103, 104, 105, 108], "tier3", "milestone",
     ["Recursive Tree Decomposition", "BST Balancing Trade-offs", "Trie Indexing Integration"],
     ["Architect an in-memory search catalog combining a Trie with a balanced BST", "Evaluate asymptotic worst-case bounds on degenerate vs balanced trees"],
     "Synthesize binary tree recursions, BST search invariants, self-balancing rotations, and prefix Trie indexing."),

    # Sec 10 (111-120)
    (111, "heaps-and-priority-queues", "Binary Heap Layout in Flat Arrays", "Heap Array Layout", 30, "INTERMEDIATE", [36, 96], "tier1", "tracing",
     ["Complete Binary Tree Property", "0-Indexed Parent/Child Formulas"],
     ["Map a complete binary tree into a 1D flat array using parent=(i-1)//2 and children=2i+1, 2i+2", "Verify the binary min-heap property: parent <= children"],
     "Examine binary heap flat-array indexing (parent = (i-1)//2, left = 2i+1, right = 2i+2) and complete tree layouts."),
    (112, "heaps-and-priority-queues", "Heapify, Sift-Up & Sift-Down Mechanics", "Heap Mechanics", 45, "INTERMEDIATE", [111], "tier3", "algorithm",
     ["Sift-Up (Bubble-Up) & Sift-Down", "Linear O(N) Bottom-Up Heapify"],
     ["Implement sift-up and sift-down mechanics to restore heap invariants in O(log N) time", "Prove mathematically that bottom-up heapify builds a heap in linear O(N) time"],
     "Implement sift-up and sift-down operations, and prove that bottom-up heapify runs in linear O(N) time."),
    (113, "heaps-and-priority-queues", "Python's heapq Module & Tie-Breaker Patterns", "heapq Mechanics", 30, "INTERMEDIATE", [22, 112], "tier1", "completion",
     ["heapq Min-Heap Primitives", "Tuple Tie-Breaker Crash Prevention"],
     ["Use heapq.heappush, heappop, and heapify to manage priority queues", "Prevent tuple comparison crashes on identical priorities using unique counter sequence ids"],
     "Master Python's heapq module, simulate max-heaps via negation, and use counter tie-breakers to prevent comparison crashes."),
    (114, "heaps-and-priority-queues", "Top K Frequent Elements in Data Streams", "Top-K Streaming", 35, "INTERMEDIATE", [68, 113], "tier2", "problem",
     ["Bounded Min-Heap of Size K", "O(N log K) Extraction"],
     ["Maintain a min-heap of size K to identify top K frequent elements in O(N log K) time", "Contrast bounded min-heap filtering against full O(N log N) array sorting"],
     "Find the K most frequent items in continuous streams in O(N log K) time using bounded min-heaps."),
    (115, "heaps-and-priority-queues", "Merge K Sorted Lists via Min-Heap", "K-Way Merging", 40, "INTERMEDIATE", [81, 113], "tier2", "problem",
     ["Frontier Pointer Min-Heap", "O(N log K) Multi-Stream Merging"],
     ["Merge K sorted linked lists or streams using a min-heap tracking current heads", "Achieve optimal O(N log K) total runtime and O(K) auxiliary space"],
     "Merge K sorted lists or streams into a single sorted list in O(N log K) time using priority queue frontiers."),
    (116, "heaps-and-priority-queues", "Two-Heap Pattern: Median of a Stream", "Two Heaps", 45, "INTERMEDIATE", [113], "tier3", "algorithm",
     ["Max-Heap (Lower) & Min-Heap (Upper)", "O(1) Median & O(log N) Insertion"],
     ["Balance a max-heap of smaller elements and min-heap of larger elements", "Retrieve running medians in O(1) time and insert stream values in O(log N) time"],
     "Implement the two-heap pattern (max-heap for lower half, min-heap for upper half) to find stream medians in O(1) time."),
    (117, "heaps-and-priority-queues", "Task Scheduler & Priority Reorganization", "Task Scheduling", 40, "INTERMEDIATE", [113, 114], "tier2", "problem",
     ["Greedy Max-Frequency Extraction", "Cooldown Queue Waiting Line"],
     ["Schedule CPU tasks with cooldown interval n using a max-heap and wait queue", "Compute minimum CPU idle intervals to complete all tasks"],
     "Schedule CPU tasks with cooling intervals using greedy max-heaps and cooldown queue staging in O(N) time."),
    (118, "heaps-and-priority-queues", "Indexed Priority Queue Principles", "Indexed Priority Queue", 45, "INTERMEDIATE", [112], "tier3", "algorithm",
     ["Position Lookup Mapping (Key -> Index)", "O(log N) decrease_key Operation"],
     ["Augment a binary heap with a hash map tracking element array indices", "Update priorities in-place (decrease_key) in strict O(log N) time without scanning"],
     "Design an Indexed Priority Queue supporting O(log N) arbitrary priority updates (decrease-key) and deletions."),
    (119, "heaps-and-priority-queues", "Kth Smallest Element in Sorted Matrix", "Matrix Kth Smallest", 35, "INTERMEDIATE", [47, 113], "tier2", "problem",
     ["Row/Column Frontier Min-Heap", "O(K log(min(K, N))) Search"],
     ["Extract K smallest elements from row-and-column sorted matrices via frontier heaps", "Contrast priority queue frontier search against monotonic binary search"],
     "Locate the Kth smallest element in row/column sorted matrices using heap frontier exploration in O(K log N) time."),
    (120, "heaps-and-priority-queues", "Section 10 Review & Priority Queue Design", "Heaps Milestone", 45, "INTERMEDIATE", [112, 113, 115, 116, 118], "tier3", "milestone",
     ["Priority Queue Engineering", "Dynamic Rebalancing", "Stream Processing Under SLA"],
     ["Architect a priority dispatch engine handling dynamic priority shifts and task starvation", "Evaluate space-time trade-offs between two-heaps, sorted arrays, and balanced BSTs"],
     "Synthesize binary heap algorithms, running median dual-heaps, and indexed priority queues into a streaming scheduler."),

    # Sec 11 (121-135)
    (121, "graphs", "Graph Representations & Adjacency Lists", "Graph Representations", 30, "ADVANCED", [15, 18, 36], "tier1", "guided",
     ["Adjacency List vs Adjacency Matrix", "Directed, Undirected & Weighted Graphs"],
     ["Construct adjacency list dictionary representations from edge lists in O(V + E) time", "Evaluate space and edge query trade-offs between sparse lists and dense matrices"],
     "Represent graphs using adjacency lists, adjacency matrices, and edge lists; evaluate density trade-offs."),
    (122, "graphs", "BFS & Unweighted Shortest Path", "Breadth-First Search", 35, "ADVANCED", [89, 121], "tier2", "algorithm",
     ["FIFO Queue Level Expansion", "Predecessor Array & Distance Tracking"],
     ["Implement Breadth-First Search (BFS) to find shortest path distances on unweighted graphs", "Reconstruct shortest path vertices using a predecessor parent map in O(V + E) time"],
     "Implement BFS using collections.deque to find shortest paths on unweighted graphs and reconstruct shortest paths."),
    (123, "graphs", "DFS, Connected Components & Flood Fill", "Depth-First Search", 35, "ADVANCED", [30, 121], "tier2", "algorithm",
     ["Recursive DFS Traversal", "Visited Set & Grid Flood Fill"],
     ["Traverse all reachable graph vertices using Depth-First Search with a visited set", "Count connected components and solve 2D grid flood fill problems in O(V + E) time"],
     "Implement recursive and iterative DFS, count connected components, and solve 2D grid flood fill problems."),
    (124, "graphs", "Cycle Detection in Directed Graphs (3-Color)", "Cycle Detection", 35, "ADVANCED", [123], "tier2", "debugging",
     ["Three-Color State Marking (White, Gray, Black)", "Back-Edge Detection"],
     ["Detect cycles in directed graphs by identifying back-edges to gray nodes on the current recursion stack", "Differentiate directed cycle detection from undirected visited-set checks"],
     "Detect cycles in directed graphs using three-color DFS marking (Unvisited, Visiting, Visited) and back-edge identification."),
    (125, "graphs", "Topological Sort: Kahn's In-Degree BFS", "Topological Sort BFS", 40, "ADVANCED", [122, 124], "tier2", "algorithm",
     ["In-Degree Array Construction", "Zero-In-Degree FIFO Queue"],
     ["Compute vertex in-degrees and process zero-in-degree nodes sequentially", "Produce a valid topological order of a DAG or detect cyclic dependency errors in O(V + E) time"],
     "Implement Kahn's algorithm for topological sorting of DAGs using in-degree arrays and zero-degree queues."),
    (126, "graphs", "Topological Sort: DFS Post-Order Reversal", "Topological Sort DFS", 35, "ADVANCED", [123, 125], "tier2", "problem",
     ["DFS Finishing Time Post-Order", "Reversed Post-Order Sequence"],
     ["Record DFS finish order and reverse the post-order sequence to produce a topological sort", "Solve Course Schedule II under prerequisite constraints"],
     "Implement topological sort using DFS post-order traversal reversal and detect invalid cyclic dependencies."),
    (127, "graphs", "Bipartite Graph Verification (2-Coloring)", "Bipartite Verification", 30, "ADVANCED", [122], "tier1", "problem",
     ["Vertex 2-Coloring Invariant", "Odd-Length Cycle Non-Bipartite Rule"],
     ["Color graph vertices with two alternating labels using BFS/DFS", "Prove a graph is non-bipartite if adjacent vertices share identical color labels"],
     "Determine whether a graph is bipartite (2-colorable) using alternating BFS/DFS vertex coloring in O(V + E) time."),
    (128, "graphs", "Dijkstra's Algorithm: Shortest Paths", "Dijkstra's Algorithm", 45, "ADVANCED", [113, 121], "tier3", "algorithm",
     ["Greedy Distance Relaxation (d[v] = d[u] + w)", "Min-Heap Optimization O((V+E) log V)"],
     ["Implement Dijkstra's algorithm to compute single-source shortest paths on non-negative weighted graphs", "Maintain a min-heap of tentative distances and skip stale extracted entries in O((V + E) log V) time"],
     "Implement Dijkstra's algorithm using priority queues to compute single-source shortest paths with non-negative edge weights."),
    (129, "graphs", "Bellman-Ford & Negative Cycle Detection", "Bellman-Ford", 45, "ADVANCED", [128], "tier3", "algorithm",
     ["V-1 Edge Relaxation Passes", "Negative Weight Cycle Detection on Pass V"],
     ["Relax all graph edges V - 1 times to find shortest paths with negative edge weights", "Identify negative-weight cycles by checking if distances continue decreasing on pass V"],
     "Implement the Bellman-Ford algorithm in O(V * E) time, handle negative weights, and detect reachable negative cycles."),
    (130, "graphs", "Disjoint Set Union (DSU / Union-Find)", "Disjoint Set Union", 45, "ADVANCED", [121], "tier3", "algorithm",
     ["Path Compression Invariant", "Union by Rank/Size & Inverse Ackermann O(alpha(N))"],
     ["Implement Disjoint Set Union (Union-Find) with root representative find operations", "Achieve nearly O(1) amortized operations using Path Compression and Union by Rank"],
     "Implement Disjoint Set Union (DSU) with Path Compression and Union by Rank, achieving near-O(1) amortized time."),
    (131, "graphs", "Minimum Spanning Tree: Kruskal's with DSU", "Kruskal's MST", 45, "ADVANCED", [130], "tier3", "algorithm",
     ["Greedy Edge Weight Sorting", "Cycle Avoidance via DSU"],
     ["Sort all graph edges by weight and greedily select non-cyclic edges using DSU", "Construct a Minimum Spanning Tree in O(E log E) time"],
     "Implement Kruskal's algorithm to find Minimum Spanning Trees (MST) by sorting edges and avoiding cycles with DSU."),
    (132, "graphs", "Minimum Spanning Tree: Prim's Algorithm", "Prim's MST", 40, "ADVANCED", [113, 131], "tier2", "algorithm",
     ["Growing Subtree Frontier Cut", "Min-Heap Crossing Edge Selection"],
     ["Grow an MST from a start vertex by repeatedly selecting the minimum crossing edge via a min-heap", "Achieve O((V + E) log V) runtime on dense graphs"],
     "Implement Prim's algorithm for Minimum Spanning Trees using priority queues to select minimum crossing edges."),
    (133, "graphs", "Undirected Bridges & Articulation Points", "Bridges & Articulation", 45, "ADVANCED", [123], "tier3", "algorithm",
     ["DFS Discovery Times (tin)", "Low-Link Values (low) & Bridge Condition (low[v] > tin[u])"],
     ["Calculate discovery times and lowest reachable ancestor depths during a single DFS traversal", "Locate all critical bridges and articulation cut-vertices in O(V + E) time"],
     "Find all bridges and articulation points in undirected graphs using Tarjan's discovery time (tin) and low-link (low) DFS."),
    (134, "graphs", "Strongly Connected Components (Kosaraju)", "Strongly Connected Components", 45, "ADVANCED", [123, 133], "tier3", "algorithm",
     ["Transpose Graph Reversal", "Kosaraju's Two-Pass DFS Algorithm"],
     ["Reconstruct transposed reversed graphs where directed edge orientations are inverted", "Extract all Strongly Connected Components (SCCs) in directed graphs using Kosaraju's algorithm in O(V + E) time"],
     "Implement Kosaraju's two-pass DFS algorithm on graphs and their transposes to find Strongly Connected Components in DAGs."),
    (135, "graphs", "Section 11 Review & Graph Synthesis", "Graph Milestone", 45, "ADVANCED", [122, 125, 128, 130, 131, 134], "tier3", "milestone",
     ["Shortest Path vs MST Selection", "Topological Pipeline Architecture", "Component Condensation"],
     ["Design a multi-modal routing engine integrating Dijkstra, BFS, and DSU under real-world constraints", "Condense directed cyclic graphs into topological DAG components"],
     "Synthesize BFS, DFS, topological sorting, Dijkstra, DSU, MSTs, and SCC algorithms into a comprehensive network router."),

    # Sec 12 (136-145)
    (136, "greedy-algorithms", "Greedy Choice Property & Exchange Arguments", "Greedy Foundations", 30, "ADVANCED", [26, 49], "tier1", "tracing",
     ["Greedy-Choice Property", "Exchange Argument Proof Technique"],
     ["Evaluate whether locally optimal choices lead to globally optimal solutions", "Formulate exchange argument proofs showing no optimal solution beats greedy"],
     "Understand the Greedy Choice Property, Optimal Substructure, and prove optimality using exchange arguments."),
    (137, "greedy-algorithms", "Activity Selection & Interval Scheduling", "Activity Selection", 35, "ADVANCED", [49, 136], "tier1", "algorithm",
     ["Earliest Finishing Time Greedy Sort", "Non-Overlapping Choice Invariant"],
     ["Sort intervals by earliest finish time to maximize non-overlapping scheduled tasks", "Prove greedy interval scheduling optimality in O(N log N) time"],
     "Solve the Activity Selection problem by sorting on earliest finish time, proving optimality via exchange arguments."),
    (138, "greedy-algorithms", "Fractional Knapsack & Value Density Sorting", "Fractional Knapsack", 35, "ADVANCED", [136], "tier1", "algorithm",
     ["Value-to-Weight Ratio Density", "Continuous Item Partitioning"],
     ["Sort items by value-per-weight density to maximize total value in fractional knapsacks", "Contrast fractional greedy solvability with 0/1 integer knapsack NP-hardness"],
     "Implement the Fractional Knapsack problem in O(N log N) time by greedily sorting items by value-to-weight density."),
    (139, "greedy-algorithms", "Huffman Coding & Optimal Prefix Trees", "Huffman Coding", 45, "ADVANCED", [113, 136], "tier3", "algorithm",
     ["Optimal Prefix Code Invariant", "Min-Heap Bottom-Up Tree Merging"],
     ["Construct an optimal prefix code tree by repeatedly merging the two least frequent nodes", "Generate variable-length binary encoding tables without prefix ambiguity"],
     "Construct optimal variable-length prefix codes using Huffman's algorithm with priority queues in O(N log N) time."),
    (140, "greedy-algorithms", "Jump Game & Reachability Frontiers", "Reachability Greedy", 35, "ADVANCED", [43, 136], "tier2", "problem",
     ["Max Reachability Frontier Invariant", "Boundary Jump Step Increments"],
     ["Track maximum reachable index frontiers to determine if array ends are reachable in O(N) time", "Compute minimum jumps to reach the end using greedy interval boundary shifts"],
     "Solve Jump Game I (reachability) and Jump Game II (minimum jumps) using greedy frontier advancement in O(N) time."),
    (141, "greedy-algorithms", "Partition Labels & Last Seen Indices", "Partition Labels", 35, "ADVANCED", [15, 140], "tier2", "problem",
     ["Last Occurrence Index Hash Map", "Frontier Extension Invariant"],
     ["Record the last occurrence index of each character to partition strings into disjoint subsegments", "Return maximum partition sizes in O(N) time and O(1) space"],
     "Partition strings into maximal parts such that each character appears in at most one part in O(N) time."),
    (142, "greedy-algorithms", "Gas Station & Circular Circuit Greedy", "Circular Greedy", 40, "ADVANCED", [140], "tier2", "problem",
     ["Total Gas >= Total Cost Invariant", "Deficit Reset Starting Point Shift"],
     ["Prove a unique starting gas station exists if and only if total gas >= total cost", "Reset prospective starting points in a single O(N) scan whenever running tank deficits occur"],
     "Determine the starting gas station to complete a circular tour in O(N) time using net balance greedy sweeps."),
    (143, "greedy-algorithms", "Candy Distribution: Two-Pass Greedy", "Two-Pass Greedy", 40, "ADVANCED", [140], "tier2", "problem",
     ["Left-to-Right & Right-to-Left Passes", "Local Rating Maximization"],
     ["Satisfy neighbor rating constraints using independent forward and backward greedy sweeps", "Compute minimum required resources in O(N) time and O(N) auxiliary space"],
     "Solve the Candy distribution problem using two independent greedy passes (left-to-right, right-to-left) in O(N) time."),
    (144, "greedy-algorithms", "Frequency Decrementing for Uniqueness", "Unique Frequencies", 30, "ADVANCED", [17, 68], "tier1", "problem",
     ["Seen-Frequencies Set Invariant", "Greedy Deletion Count Minimization"],
     ["Ensure all character frequencies are strictly unique by greedily decrementing duplicates", "Compute minimum character deletions in O(N) time and O(K) space"],
     "Find the minimum character deletions to make all character frequencies unique using greedy decrement sets."),
    (145, "greedy-algorithms", "Section 12 Review & Greedy Proof Formalism", "Greedy Milestone", 45, "ADVANCED", [136, 137, 139, 140, 142, 143], "tier3", "milestone",
     ["Greedy vs Dynamic Programming Discrimination", "Formal Exchange Proofs", "Deadline Scheduling"],
     ["Determine whether optimization problems admit greedy solutions or require dynamic programming", "Implement job sequencing with deadlines and profits using greedy selection and DSU"],
     "Synthesize greedy choice proofs, interval scheduling, reachability frontiers, and distinguish greedy from DP."),

    # Sec 13 (146-155)
    (146, "dynamic-programming", "Memoization vs Tabulation Paradigms", "DP Foundations", 35, "ADVANCED", [30, 31], "tier2", "tracing",
     ["Overlapping Subproblems & Optimal Substructure", "Top-Down Memoization vs Bottom-Up Tabulation"],
     ["Identify overlapping subproblems in recursive DAGs and cache results in hash maps", "Construct iterative bottom-up tables eliminating call stack overhead"],
     "Understand overlapping subproblems, optimal substructure, top-down memoization (lru_cache) vs bottom-up tabulation."),
    (147, "dynamic-programming", "1D DP: Climbing Stairs & House Robber", "1D State Recurrences", 35, "ADVANCED", [146], "tier2", "completion",
     ["State Transition Recurrence", "O(1) Rolling Variable Space Optimization"],
     ["Formulate 1D state transition equations dp[i] = max(dp[i-1], dp[i-2] + val)", "Compress 1D DP arrays into two rolling variables achieving O(1) auxiliary space"],
     "Formulate 1D DP recurrences (Climbing Stairs, House Robber) and optimize auxiliary space to O(1) rolling variables."),
    (148, "dynamic-programming", "2D Grid DP: Unique Paths & Min Path Sum", "2D Grid DP", 40, "ADVANCED", [47, 147], "tier2", "problem",
     ["2D Grid State dp[r][c]", "In-Place Matrix Space Compression"],
     ["Compute unique paths and minimum path sums on grids with obstacles", "Optimize 2D grid DP memory from O(M * N) to O(N) single-row buffers"],
     "Solve grid dynamic programming problems (Unique Paths, Minimum Path Sum) and compress 2D tables into 1D rows in O(M*N) time."),
    (149, "dynamic-programming", "0/1 Knapsack: Table to 1D Reverse Pass", "0/1 Knapsack", 45, "ADVANCED", [147], "tier3", "debugging",
     ["Capacity Inclusion-Exclusion Choice", "1D Reverse Traversal to Prevent Item Re-use"],
     ["Formulate the 0/1 Knapsack recurrence choosing to include or skip current item", "Debug 1D space-optimized knapsack updates by reversing capacity sweeps from W down to weight"],
     "Master the classical 0/1 Knapsack problem, formulate 2D state tables, and optimize space via 1D reverse-capacity sweeps."),
    (150, "dynamic-programming", "Unbounded Knapsack & Coin Change Combinations", "Unbounded Knapsack", 45, "ADVANCED", [149], "tier3", "problem",
     ["Forward Capacity Loop Invariant", "Min Coins (Minimization) vs Ways (Counting)"],
     ["Implement unbounded knapsack choices where items can be selected repeatedly via forward loops", "Differentiate Coin Change 1 (minimum coins) from Coin Change 2 (combination ways)"],
     "Solve Unbounded Knapsack and Coin Change (min coins and combinations count) using 1D forward capacity loops in O(N * W) time."),
    (151, "dynamic-programming", "Longest Increasing Subsequence (O(N log N))", "LIS Optimization", 45, "ADVANCED", [52, 147], "tier3", "problem",
     ["O(N^2) Tabulation Recurrence", "Patience Sorting & Tails Array O(N log N)"],
     ["Formulate the standard O(N^2) LIS recurrence checking all predecessor indices", "Optimize LIS to O(N log N) time using Patience Sorting and bisect binary search over tails arrays"],
     "Optimize Longest Increasing Subsequence from O(N^2) DP to O(N log N) using patience sorting and binary search."),
    (152, "dynamic-programming", "Longest Common Subsequence (LCS)", "LCS Alignment", 40, "ADVANCED", [148], "tier3", "algorithm",
     ["2D Sequence Matching Recurrence", "Backtracking Alignment Reconstruction"],
     ["Construct a 2D LCS matrix tracking character matches and max diagonal transitions", "Reconstruct the optimal subsequence string by backtracking through the DP table in O(M * N) time"],
     "Implement Longest Common Subsequence (LCS) for two strings, formulate 2D transitions, and reconstruct alignments."),
    (153, "dynamic-programming", "Edit Distance (Levenshtein Distance)", "Edit Distance", 45, "ADVANCED", [152], "tier3", "problem",
     ["Insert, Delete, Replace Cost Operations", "2D Distance Matrix Invariant"],
     ["Formulate the Levenshtein distance recurrence evaluating insert, delete, and substitute costs", "Compute minimum edit operations to transform word1 into word2 in O(M * N) time"],
     "Compute the Levenshtein Edit Distance between two strings with insertion, deletion, and replacement operations in O(M*N) time."),
    (154, "dynamic-programming", "Interval DP: Matrix Chain & Burst Balloons", "Interval DP", 45, "ADVANCED", [149, 152], "tier3", "problem",
     ["Subarray Span Iteration (len 2 to N)", "Last Operation Partition Choice"],
     ["Solve optimization problems over contiguous intervals by iterating span lengths", "Solve Burst Balloons by choosing which balloon bursts last within interval (i, j)"],
     "Master Interval DP by iterating over subarray lengths, formulating boundary transitions (Burst Balloons, Matrix Chain)."),
    (155, "dynamic-programming", "Section 13 Review & Multi-State DP Design", "DP Milestone", 45, "ADVANCED", [147, 148, 149, 150, 151, 152, 154], "tier3", "milestone",
     ["Finite State Machine DP (Buy/Sell/Cooldown)", "Multi-Dimensional State Formulation", "Space Optimization"],
     ["Architect state-machine DP models tracking multiple simultaneous states (e.g. stock trading with cooldowns)", "Select optimal state representations and recurrence orders across all DP archetypes"],
     "Synthesize 1D, 2D, knapsack, subsequence, interval, and state-machine DP patterns into a comprehensive DP master class."),

    # Sec 14 (156-160)
    (156, "advanced-dsa", "Bit Manipulation, Bitmasks & Brian Kernighan", "Bitmask Mastery", 35, "EXPERT", [2, 147], "tier2", "completion",
     ["Brian Kernighan's Algorithm (n & (n-1))", "Bitmask Subsets & State Representation"],
     ["Clear the lowest set bit in O(1) operations using n & (n - 1) to count set bits", "Represent subsets and visited states compactly using integer bitmasks (1 << i)"],
     "Master bitwise operations, Brian Kernighan's algorithm, power-of-two tests, and subset generation with bitmasks."),
    (157, "advanced-dsa", "Backtracking & State-Space Pruning (N-Queens)", "Backtracking & Pruning", 45, "EXPERT", [123, 156], "tier3", "algorithm",
     ["State-Space Decision Tree Exploration", "Constraint Propagation & Diagonal Bitmasks"],
     ["Implement complete backtracking frameworks with choose, explore, and unchoose steps", "Prune invalid search branches in N-Queens using column and diagonal bitmask sets"],
     "Implement systematic backtracking with search-space pruning, bitmask tracking, and solve the N-Queens problem."),
    (158, "advanced-dsa", "Segment Trees & Fenwick Trees Primer", "Range Query Trees", 45, "EXPERT", [37, 111], "tier3", "algorithm",
     ["Array-Based Segment Tree (2*i, 2*i+1)", "O(log N) Range Query & Point Update"],
     ["Construct flat array-based Segment Trees supporting logarithmic range queries and point updates", "Differentiate Segment Trees from Binary Indexed Trees (Fenwick Trees) for range computations"],
     "Build array-based Segment Trees and Fenwick Trees supporting O(log N) range queries and point updates."),
    (159, "advanced-dsa", "Complex Problem Decomposition & System Design", "System Decomposition", 45, "EXPERT", [73, 116, 128, 149], "tier3", "milestone",
     ["Hybrid Algorithmic Architecture", "Concurrency & Cache Invalidation", "Trade-off Communication"],
     ["Deconstruct ambiguous multi-faceted problems into clear data structure and algorithm pipelines", "Design a rate limiter and cache eviction system meeting production scale constraints"],
     "Decompose complex end-to-end coding interview challenges into interconnected DS/algorithm components."),
    (160, "advanced-dsa", "The 160-Day Capstone: Interview Readiness", "160-Day Capstone", 60, "EXPERT", [10, 25, 35, 50, 65, 75, 85, 95, 110, 120, 135, 145, 155, 159], "tier3", "milestone",
     ["Comprehensive Interview Synthesis", "Asymptotic Optimality Verification", "Production-Ready Engineering"],
     ["Demonstrate full fluency across Python fundamentals, memory models, data structures, and algorithms", "Complete the final capstone assessment simulating a rigorous technical interview loop"],
     "Complete the comprehensive 160-day curriculum capstone, demonstrating complete technical mastery from Python foundations to advanced DSA.")
]

def main():
    print("Generating scratch/curriculum_160.json...")
    curriculum_list = []
    
    for d in DAYS_DATA:
        day_num, sec_id, title, topic_name, est_min, diff, prereqs, flow_tier, archetype, concepts, objectives, desc = d
        curriculum_list.append({
            "day_number": day_num,
            "section_id": sec_id,
            "title": title,
            "topic_name": topic_name,
            "estimated_minutes": est_min,
            "difficulty": diff,
            "prerequisites": prereqs,
            "flow_tier": flow_tier,
            "archetype": archetype,
            "concepts": concepts,
            "learning_objectives": objectives,
            "description": desc
        })
    
    with open("scratch/curriculum_160.json", "w", encoding="utf-8") as f:
        json.dump(curriculum_list, f, indent=2)
    print(f"Successfully wrote {len(curriculum_list)} days to scratch/curriculum_160.json")

    # Generate frontend/lib/curriculum/curriculumData.ts
    print("Generating frontend/lib/curriculum/curriculumData.ts...")
    
    sections_by_id = {s["id"]: s for s in SECTIONS_SPEC}
    for s in SECTIONS_SPEC:
        s["days"] = []

    for d in curriculum_list:
        sec = sections_by_id[d["section_id"]]
        sec["days"].append({
            "day_number": d["day_number"],
            "title": d["title"],
            "topic_name": d["topic_name"],
            "section_id": d["section_id"],
            "estimated_minutes": d["estimated_minutes"],
            "description": d["description"],
            "concepts": d["concepts"]
        })

    ts_lines = [
        'import { CurriculumSection } from "./types";',
        '',
        'export const TOTAL_CURRICULUM_DAYS = 160;',
        '',
        'export const CURRICULUM_SECTIONS: CurriculumSection[] = ['
    ]

    for s in SECTIONS_SPEC:
        ts_lines.append("  {")
        ts_lines.append(f'    id: "{s["id"]}",')
        ts_lines.append(f'    section_number: {s["section_number"]},')
        ts_lines.append(f'    title: "{s["title"]}",')
        ts_lines.append(f'    tagline: "{s["tagline"]}",')
        ts_lines.append(f'    day_start: {s["day_start"]},')
        ts_lines.append(f'    day_end: {s["day_end"]},')
        ts_lines.append(f'    icon: "{s["icon"]}",')
        ts_lines.append('    days: [')
        
        for d in s["days"]:
            ts_lines.append("      {")
            ts_lines.append(f'        day_number: {d["day_number"]},')
            ts_lines.append(f'        title: "{d["title"]}",')
            ts_lines.append(f'        topic_name: "{d["topic_name"]}",')
            ts_lines.append(f'        section_id: "{d["section_id"]}",')
            ts_lines.append(f'        estimated_minutes: {d["estimated_minutes"]},')
            # Escape quotes in description
            desc_clean = d["description"].replace('"', '\\"')
            ts_lines.append(f'        description: "{desc_clean}",')
            concepts_json = json.dumps(d["concepts"])
            ts_lines.append(f'        concepts: {concepts_json}')
            ts_lines.append("      },")

        ts_lines.append('    ]')
        ts_lines.append("  },")

    ts_lines.append("];")
    ts_lines.append("")

    with open("frontend/lib/curriculum/curriculumData.ts", "w", encoding="utf-8") as f:
        f.write("\n".join(ts_lines))
    print("Successfully wrote frontend/lib/curriculum/curriculumData.ts")

if __name__ == "__main__":
    main()
